### ISSUE TITLE
长按不动然后放开后，那个item会一直处于放大状态

### ISSUE THREAD

**Issue by solke** [mochixuan/react-native-drag-sort#1]

**Comment by mochixuan** [comment]
有自动恢复的代码。

**Comment by Ekhui** [comment]
应该是释放的监听没调用 就是按住不move的话onPanResponderRelease这个监听我打了日志 没有调用 所以没有调用
start复原动画

**Comment by xiongyuk** [comment]
同问

**Comment by jeffy7** [comment]
> 应该是释放的监听没调用 就是按住不move的话onPanResponderRelease这个监听我打了日志 没有调用 所以没有调用
> start复原动画

确实没有，你是怎么解决的？

**Comment by YanmaY** [comment]
> > 应该是释放的监听没调用 就是按住不move的话onPanResponderRelease这个监听我打了日志 没有调用 所以没有调用
> > start复原动画
> 
> 确实没有，你是怎么解决的？

我还在官网发了issue，不过也没人回答（摊手.gif）

**Comment by mochixuan** [comment]
由于工作比较忙，没时间改。大家提的问题我刚刚测试了下。
本插件拖动是使用长按触发开始时间的，一般手指按压下去，都会有轻微抖动你们可以打印move事件观察，但发现刚触发长按事件时立刻放手这时有极大可能没有触发，现在已经修复了这个问提。

**Comment by jeffy7** [comment]
> 由于工作比较忙，没时间改。大家提的问题我刚刚测试了下。
> 本插件拖动是使用长按触发开始时间的，一般手指按压下去，都会有轻微抖动你们可以打印move事件观察，但发现刚触发长按事件时立刻放手这时有极大可能没有触发，现在已经修复了这个问提。

你好，还有一个问题，我给data 增加数据，发现并不新增，原因是componentWillReceiveProps 里面的this.props.dataSource != nextProps.dataSource 他们相等，然后我记录原始的dataSource 又会出现白屏情况，想问下怎么解决增加数据并刷新的情况

**Comment by mochixuan** [comment]
> > 由于工作比较忙，没时间改。大家提的问题我刚刚测试了下。
> > 本插件拖动是使用长按触发开始时间的，一般手指按压下去，都会有轻微抖动你们可以打印move事件观察，但发现刚触发长按事件时立刻放手这时有极大可能没有触发，现在已经修复了这个问提。
> 
> 你好，还有一个问题，我给data 增加数据，发现并不新增，原因是componentWillReceiveProps 里面的this.props.dataSource != nextProps.dataSource 他们相等，然后我记录原始的dataSource 又会出现白屏情况，想问下怎么解决增加数据并刷新的情况

Non-ScrollView Page界面长按触发删除功能，新加了添加功能演示，使用时小心this.state.data的添加数据方式记得先把原数据取出[...this.state.data]

**Comment by jeffy7** [comment]
好的  谢谢，我看看

**Comment by xchunzhao** [comment]
> 由于工作比较忙，没时间改。大家提的问题我刚刚测试了下。
> 本插件拖动是使用长按触发开始时间的，一般手指按压下去，都会有轻微抖动你们可以打印move事件观察，但发现刚触发长按事件时立刻放手这时有极大可能没有触发，现在已经修复了这个问提。

提了个PR 跟这个相关 #8
