### ISSUE TITLE
[DragSortableView] BUG with refresh data 

### ISSUE THREAD

**Issue by mattallard123** [mochixuan/react-native-drag-sort#100]
Had an issue with new state data being passed into DragSortableView with "dataSource" property. When adding data ONLY, deleting / removing works fine. 

The issue seems to be cause from the nextprops.dataSource != prevState.curPropsDataSource comparison within the getDerivedStateFromProps() function. For some reason, the nextprops.dataSource and prevState.curPropsDataSource are the same when passing in an extra object in the dataSource array. 

The issue is fixed by commenting out the "if (nextprops.dataSource != prevState.curPropsDataSource || itemWidth !== prevState.itemWidth || itemHeight !== prevState.itemHeight) {" comparison so that the component always reassigns the data instead of only on the constructor. 

Not sure if this is a bug with Fiber?

**Comment by mattallard123** [comment]
After further review, appears to be an issue with react version, 16.13.1 which is the version that ships when you run "npx react-native init ..."

**Comment by mattallard123** [comment]
Updated version of react and same issue. After more investigation, it is related to the getDerivedStateFromProps(nextprops, prevState) function. When data is changed on the dataSource property outside the component, nextprops.dataSource and prevState.curPropsDataSource both have the same value of the new data coming in.

**Comment by mochixuan** [comment]
When modifying data, you need to copy it out and modify it before setting it. Correct writing const data = [...this.state.data] is being modified

**Comment by ajlamarc** [comment]
I am having the same problem with the list not updating.  I set dataSource={this.state.data} and ran the below code (a console.log() showed me that the state did indeed update) but the list does not update accordingly.  When I log inside the renderItem function, all the render items did not change, so the new state isn't making it into the render item function for some reason. 

`let newData = this.state.data;
 newData[number] = { icon: uploadUrl };
 this.setState({ ...this.state, data: newData });`

**Comment by mochixuan** [comment]
You can refer to the demo, refresh will definitely happen.
