### ISSUE TITLE
 implement drag lists like in Trello

### ISSUE THREAD

**Issue by simonprod** [mochixuan/react-native-drag-sort#101]
Hi, cool library, I would like to know if improvements are planned
We are looking for functionality similar to the Trello Board
There is something similar for react-native, example - https://www.npmjs.com/package/react-native-draganddrop-board
But you have support for react-native-web and mobile devices without any fix
If you are interested in implementing something like this, it would be great

**Comment by mochixuan** [comment]
After reading the link you gave, its animation and interaction are very good. I will test on the mobile phone to see the specific performance and effects when I have time. Do you have any suggestions for my component? You can make suggestions. I There will be time to optimize and improve

**Comment by simonprod** [comment]
It would be nice if your library had the opportunity to sketch something similar to Trello board

**Comment by mochixuan** [comment]
What you sent was a very good interaction. I will try, when I have time.
