### ISSUE TITLE
Updating content prop in handleDragEnd causes glitch 

### ISSUE THREAD

**Issue by avertin** [mochixuan/react-native-drag-sort#104]
Thanks for making and maintaining such an awesome library. Overall my experience with the library has been great, but I've run into one weird issue. 

I'm using `AutoDragSortableView` to drag a grid of items. I have an event handler for `onDragEnd`. I use the `fromIndex` and `toIndex` to update the order of the content in redux and make an api call.  The content prop I'm passing into the library is directly connected to the redux content. I've seen that updating the redux content and thus updating the content prop in the library, causes a weird glitch in the ordering. 

I've made a gif and a sample app of the issue to demonstrate it in a simplified way (without redux) - https://github.com/avertin/reorder-sample/blob/main/App.js

![repro](https://user-images.githubusercontent.com/11411307/101850352-739a3900-3b0e-11eb-9344-3d5f3ee82a96.gif)

It is reproducible 100% of the time in the sample app. As you can see in the gif, I moved item 3 to position 0 but then the library flips items around to a different order. In the terminal window, you can see that `handleDragEnd` gets the correct to/fromIndex and updates the order correctly. Once the local state is updated, it is passed back into the library as the content prop and the glitch occurs. Notice that the output from `handleDataChange` reflects the incorrect ordering that results from the glitch.  

Ideally, we would like to be able to use `handleDragEnd` in this way but if there is a different approach that would work better, please let me know.

**Comment by jonthanon** [comment]
I noticed that the `onDragEnd` prop is fired before `changePosition` happens in the `endTouch` method, and `changePosition` is what eventually updates the internal datasource in state. So my gut says the sample app is updating the datasource with the new version in response to `onDragEnd` before the local update in `changePosition` happens, but then it still does the update to the datasource as though it still needed to happen, but we’ve actually already updated it. That would mean that effectively the same reorder happens twice, which is exactly what it looks like is happening in the GIF. Number 3 moves to the front, and then number 2 (which is now index 3) moves to the front.

My first thought is maybe the local datasource update (`changePosition`) should happen *before* the `onDragEnd` prop is fired, but I haven't fully thought that through so I imagine there could be a reason that's a bad idea.

**Comment by mochixuan** [comment]
You can take a look at example and the code in example. It works normally. You can have a look https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/AutomaticSlidingOnePage.js perhaps https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/AutomaticSlidingThreePage.js 。

Normally, you can update your datasource at the end of the update without changing your datasource. You can also handle it as in the example. It works well.

**Comment by avertin** [comment]
Thanks for the response @mochixuan. Unfortunately, the examples that show using `onDataChange` to update the datasource aren't a sufficient solution for us because `onDataChange` doesn't contain info about the toIndex and fromIndex. Regardless, it still feels like a bug that updating the datasource in `onDragEnd` results in a double reorder. Would you be willing to incorporate @jonthanon's suggestion into the library so that `onDragEnd` isn't fired until after `changePosition` is complete?  If not, we can also make a PR.

**Comment by mochixuan** [comment]
This program may not have time to write until the weekend, you can try to modify it yourself.
