### ISSUE TITLE
松手的时候，有时候会重叠

### ISSUE THREAD

**Issue by huangnl** [mochixuan/react-native-drag-sort#108]
![微信图片_20201225170840](https://user-images.githubusercontent.com/17984961/103129478-e2ad8b00-46d3-11eb-8400-1131d6414665.jpg)
qq215074882

**Comment by mochixuan** [comment]
看看keyExtractor是不是唯一，还有就是Debug模式动画会比较卡。你可以跑下Example，里面很多例子

**Comment by lilicoder** [comment]
同样的问题，求解
![image](https://user-images.githubusercontent.com/24731304/103201827-d9b6f680-492b-11eb-9cab-596c984b525c.png)
` <AutoDragSortableView
            dataSource={installJobDataList}
            onClickItem={(a, item, index) =>
              NavigationUtils.goPage("installEditPage", {
                type: "edit",
                item: item,
                indexItem: index,
              })
            }
            parentWidth={parentWidth}
            childrenWidth={childrenWidth}
            marginChildrenBottom={10}
            marginChildrenRight={16}
            marginChildrenLeft={16}
            // marginChildrenTop={10}
            childrenHeight={childrenHeight}
            onDataChange={(data) => {
              let _tempArray = data;
              let _saveArr = this.props.installJobDataListSave;
              _tempArray = handleInstallJobLineNo(_tempArray);
              //排序更新参数，如果是新增的，sysState不修改，其他的更新为updated
              _tempArray.forEach((item) => {
                _saveArr.forEach((x, index) => {
                  if (x.jobId == item.jobId || x.jobId == item.code) {
                    _saveArr[index].lineNo = item.lineNumber;
                    if (_saveArr[index].sysState !== "created") {
                      _saveArr[index].sysState = "updated";
                    }
                  }
                });
              });
              _saveArr.sort((a, b) => {
                return a.lineNo - b.lineNo;
              });
              this.props.setInstallJobDataListSave(_saveArr);
              this.props.setInstallJobDataList(_tempArray);
            }}
            keyExtractor={(item, index) => item.id}
            renderItem={(item, index) => {
              return this.renderItem(item, index);
            }}
            bottomViewHeight={50}
            renderBottomView={<Text></Text>} 
          />`

**Comment by lilicoder** [comment]
![image](https://user-images.githubusercontent.com/24731304/103201944-27cbfa00-492c-11eb-8530-4b5ff33d6224.png)

**Comment by huangnl** [comment]
我在endTouch后面改了一下，貌似现在没怎么出现重叠的问题了
this.setState({
            dataSource: newDataSource
        },()=>{
            if (this.props.onDataChange) {
                this.props.onDataChange(this.getOriginalData())
            }
            // Prevent RN from drawing the beginning and end

            this.state.dataSource.map((item,index)=>{
                item.position.setValue({
                    x: parseInt(item.originLeft+0.5),
                    y: parseInt(item.originTop+0.5),
                })
            })

    /*        const startItem = this.state.dataSource[startIndex]
            this.state.dataSource[startIndex].position.setValue({
                x: parseInt(startItem.originLeft+0.5),
                y: parseInt(startItem.originTop+0.5),
            })
            const endItem = this.state.dataSource[endIndex]
            this.state.dataSource[endIndex].position.setValue({
                x: parseInt(endItem.originLeft+0.5),
                y: parseInt(endItem.originTop+0.5),
            })*/
        })
