### ISSUE TITLE
Each item as a Touchable element not getting dragged

### ISSUE THREAD

**Issue by sirajalam049** [mochixuan/react-native-drag-sort#109]
I have an input of images where images are re-orderable, so each item is image input so I need to add an onPress event so I'm using TouchableHighlight, but dragging is not working if I'm using it.

**Comment by mochixuan** [comment]
Yes, your own press will not take effect. Because the touch event is intercepted in the upper layer, the button event has been retained in the component.

**Comment by mochixuan** [comment]
Adaptive size has been developed and drag can be triggered anywhere
