### ISSUE TITLE
[Feature request] Control the delay time before long-pressing an item makes it dragable

### ISSUE THREAD

**Issue by nadav2051** [mochixuan/react-native-drag-sort#11]
Hi! Thanks for the amazing library, could you please add support to shorten the delay of a long press needed to go into dragable mode?

**Comment by mochixuan** [comment]
The trigger drag mode is triggered by the long press of the component. If you want to change it, you must write the long press trigger function yourself.

**Comment by Gaganrana92** [comment]
You can give  delayLongPress={200} to the Touchable Component of the render method of your AnySizeDragSortableView
