### ISSUE TITLE
怎么去删除dragView中一项

### ISSUE THREAD

**Issue by asagcs** [mochixuan/react-native-drag-sort#118]
在SortAndFixedPage的例子中左上角有个删除标志，此时我点击并改变了dataSource里的数据（由于是修改数组内部数据，因此引用对象指向地址没有改变，只有length变化），此时虽然dataSource的数据变化了，但是DragSortableView组件并没有重新渲染，即没有深度监听
@mochixuan

**Comment by mochixuan** [comment]
你可以看下我的demo，里面有很简单的例子。
