### ISSUE TITLE
There is an option to change only one child margin?

### ISSUE THREAD

**Issue by dorbenzvi** [mochixuan/react-native-drag-sort#119]
Hi,
First, thanks for this awesome library.
Second, there is an option to change on click margin on click?
I have a list, on click, it opens options for an item.
I want to add a margin to this child element on click and remove the margin later.
Here a screenshot:

Before the click:
![image](https://user-images.githubusercontent.com/55704483/112108984-a2b65100-8bb9-11eb-829b-cf5ac342931c.png)

After the click:

![image](https://user-images.githubusercontent.com/55704483/112109047-b95ca800-8bb9-11eb-8ae2-66ee2e99e269.png)

As you can see the options hides the second child element.
Thanks in advance.

**Comment by mochixuan** [comment]
![image](https://user-images.githubusercontent.com/15728691/112123061-dfa33780-8bfb-11eb-91fa-4e3c2a29059e.png)

I don’t know if my understanding is correct: you want to trigger an event when you click on an item and modify its style at the same time. This feature is temporarily not supported. You can refer to the figure, you can modify the place in the figure in the code, and pass the parameters into the callback function.

**Comment by dorbenzvi** [comment]
@mochixuan Thanks for you response,
Actually, I'm using AutoDragSortableView and I would like to change specific child height while clicking on a button.
If I'm changing the childrenHeight prop it changes all the child's height, is it possible to change specific child height?

**Comment by sara-elbanna** [comment]
@mochixuan  same here, is it possible to set {height "auto"} to children?

**Comment by mochixuan** [comment]
You can write a function with parameters to get any ref function, through parent-child communication, so you can get the ref of any component

> @mochixuan Thanks for you response,
> Actually, I'm using AutoDragSortableView and I would like to change specific child height while clicking on a button.
> If I'm changing the childrenHeight prop it changes all the child's height, is it possible to change specific child height?

You can write a function with parameters to get any ref function, through parent-child communication, so you can get the ref of any component

**Comment by mochixuan** [comment]
> same here, is it possible to set {height "auto"} to children?

Not supported for the time being
