### ISSUE TITLE
安卓机型上拖拽还是会卡

### ISSUE THREAD

**Issue by MarioGogogo** [mochixuan/react-native-drag-sort#12]
机子：锤子坚果3
RN版本：0.44
效果：直接demo拷到项目中拖拽真机上使用还是非常卡。并且touchend后会提示错误
![](http://book.52react.cn/1376C53EE4D0F184E41A1384075C7267.jpg)

希望抽空解决下，谢谢！

**Comment by mochixuan** [comment]
你运行一下demo看下，是不是姿势不对🤦‍♂️
