### ISSUE TITLE
Changing scroll speed

### ISSUE THREAD

**Issue by mefuru** [mochixuan/react-native-drag-sort#121]
First of all, thanks for the super useful library. Much appreciated.

I'm building something on the [AutomaticSlidingThreePage.js](https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/AutomaticSlidingThreePage.js) example and I would like to increase scroll speed as it's too slow for my needs.

Any suggestions on how to do this?

**Comment by mochixuan** [comment]
You can speed up by configuring autoThrottle and autoThrottleDuration. The default autoThrottle is 2, so when autoThrottle doubles, the speed will double. For example (autoThrottle=4)

**Comment by mefuru** [comment]
Thank you for your response. It works like you described.

And autoThrottleDuration is the delay (in milliseconds) before the scrolling action starts, right? What's the default value?

Once you reply I will submit a PR with an updated Readme.

**Comment by mochixuan** [comment]
Every milliseconds (autoThrottleDuration), the px (autoThrottle) that moves automatically.
