### ISSUE TITLE
安卓上拖拽会卡在ondragging事件

### ISSUE THREAD

**Issue by qiushifa** [mochixuan/react-native-drag-sort#122]
我的外面有一层scrollview，使用AutoDragSortableView时 安卓上拖拽会卡住，iOS没有问题
![Screenshot_2021-04-20-17-19-11-122_com choiceform app osclient](https://user-images.githubusercontent.com/15922489/115371734-d1e1d180-a1fc-11eb-95e1-d9527b40a7bc.png)

**Comment by mochixuan** [comment]
debug模式是会比较卡，你需要配置keyExtractor且保证唯一，release时就不会卡顿，react-native的debug模式动画性能本就不好，而且这组件没有设置useNativeDrive。你可以看看release

**Comment by qiushifa** [comment]
好的，我试试看，谢谢
