### ISSUE TITLE
Possibility to sort items of dynamic width

### ISSUE THREAD

**Issue by jellyfish-tom** [mochixuan/react-native-drag-sort#129]
Hello, 

in demo usages I see that every drag sortable input is of the same width, that has to be set on render. 
Would it be possible to make items fit to their content? 

If it s not possible, maybe you can point me in the right direction and tell me what had to be changed to make it happen and I can implement it for us :) 

Let me know, best regards and thanks for this lib :))

**Comment by mochixuan** [comment]
Sorry, due to busy work, I just saw your issus now. This fixed width is to adapt to different screens, such as mobile phones and tablets. The height and width are temporarily not adaptive. This component costs a lot to achieve this function. , You may need to change a framework.
