### ISSUE TITLE
可以固定某个字条目不被拖动或者换位置吗

### ISSUE THREAD

**Issue by Wang1240373779** [mochixuan/react-native-drag-sort#13]

**Comment by mochixuan** [comment]
新增了固体条目功能(v1.1.1)，之前也有个人提了，现在加了一下。

**Comment by Wang1240373779** [comment]
问一下 这个 是哪个参数？

**Comment by mochixuan** [comment]
fixedItems:PropTypes.array，新增了演示页面

**Comment by Wang1240373779** [comment]
我现在页面数据不更新是因为什么，当前页面无数据，进入二级页面，回来时给数据，但是数据不展示

**Comment by mochixuan** [comment]
是不是姿势不对，不可能不刷新的，要不将数据存起来，要不每次改变是调用setState，可以根据你的需求看演示的demo.

**Comment by Wang1240373779** [comment]
我这边现在的问题是 每次更新数据之后DataSource有数据，但是item获取不到数据
![image](https://user-images.githubusercontent.com/32088612/59677131-c20d9680-91fb-11e9-937b-7c0fb142b3b2.png)

**Comment by Wang1240373779** [comment]
![image](https://user-images.githubusercontent.com/32088612/59677238-f8e3ac80-91fb-11e9-8923-7773d25f7a0e.png)

**Comment by mochixuan** [comment]
onDataChange = {(data)=>{this.setState({selectedItems: data})}}  // 更新数据
数据更新的调了吗？按照里面有演示demo，不太可能出问题。

**Comment by mochixuan** [comment]
Example里面有五个演示页面，你可以根据里面改下，没有加任何不该加的属性。

**Comment by Wang1240373779** [comment]
数据更新调用了 但是根本不走那个数据更新的方法

**Comment by mochixuan** [comment]
dataSource和onDataChange里数据要一直，你看下demo应该就知道了
