### ISSUE TITLE
Hey i want to remove image when i click on cross button only

### ISSUE THREAD

**Issue by devTechnoys** [mochixuan/react-native-drag-sort#130]
Hey i want to remove image when i click on cross button only not the whole image click. I also add custom button but how to get image index so i'm stuck please help me.

**Comment by devTechnoys** [comment]
anybody help me

**Comment by mochixuan** [comment]
You can see my demo, he realized your function

**Comment by mochixuan** [comment]
https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/SortAndFixedPage.js
