### ISSUE TITLE
请问怎么样可以让AutoDragSortableView支持单行横向拖拽

### ISSUE THREAD

**Issue by ZijianZhang991203** [mochixuan/react-native-drag-sort#133]
如题。非常感谢，可以提供报酬。

**Comment by mochixuan** [comment]
由于大多数的场景都是纵向的，所以暂时不支持横向。但是你可以对这个组件进行修改即可，该组件完全独立不依赖任何方法和组件。改一些里面的参数即可。如果需要，可以进行修改，不懂的可以问我。应该几分钟就可以改好

**Comment by mochixuan** [comment]
https://github.com/mochixuan/react-native-drag-sort/blob/master/lib/AutoDragSortableView.js

![image](https://user-images.githubusercontent.com/15728691/126886333-0949d8eb-8509-4c40-86f7-1573ae9b73d5.png)

![image](https://user-images.githubusercontent.com/15728691/126886342-72427f56-1121-4262-ac7a-ce8f485869d3.png)

![image](https://user-images.githubusercontent.com/15728691/126886357-297ee600-f23e-455c-8d72-bb945e0236a2.png)

等等，
所以的单独的height相关的换成width相关的。所以的单独和Y相关的换成X

**Comment by ZijianZhang991203** [comment]
我有尝试过修改... 修改过以后还是不行。请问能加个微信或者qq问一下吗- - 我qq是747063045。 麻烦了
