### ISSUE TITLE
Inconsistent behavior: Tiles disappear onDrag 

### ISSUE THREAD

**Issue by vic2tee4u** [mochixuan/react-native-drag-sort#139]
Code works but my tiles disappear as I drag them.

`const PictureUploader = ({ onChange, source, type }) => {
    const ImageHolderArray = new Array(6).fill('X')

    const renderItem = ({ item, index }) => <ImageHolder source={source} type={type} onPress={() => {}} />

    return (
        <View style={{ marginTop: genericSize._size20 }}>
            <DragSortableView
                dataSource={ImageHolderArray}
                childrenHeight={genericSize._size120}
                childrenWidth={width / WIDTH_FACTOR}
                marginChildrenBottom={20}
                // sortable={true}
                marginChildrenRight={8}
                onDragging={() => console.log('See this')}
                renderItem={renderItem}
                keyExtractor={(item, index) => index.toString()}
                onClickItem={(data, item, index) => {}}
                isDragFreely
                maxScale={1.2}
            />
            <View style={styles.textHolder}>
                <Text>6 pictures required</Text>
                <Text>Drag to reorder</Text>
            </View>
        </View>
    )
}`

React Native: 0.64.2
"react-native-drag-sort": "^2.4.4"
Navigation Tool: React Navigation

Reference Image link [here](https://imgur.com/qJyX8O5)

**Comment by mochixuan** [comment]
Keyextractor = {(item, index) = > index. Tostring()} is wrong. The unique identifier of the data must be returned. For example, keyextractor = {(item, index) = > index. id}
