### ISSUE TITLE
怎么把手势多点去掉

### ISSUE THREAD

**Issue by luchenqian** [mochixuan/react-native-drag-sort#14]

**Comment by mochixuan** [comment]
> _No description provided._

没太懂你的问题

**Comment by luchenqian** [comment]
长按图片拖拽 图片未浮起 无法拖拽，必须两个指头同时按下才可拖拽

**Comment by mochixuan** [comment]
这个插件也有一些人用了，没出现过这个问题，1. 是Demo问题吗，是的话可能是手机兼容问题。2.不是demo的话，应该是没有使用好。可以看Example里面有五个例子。

**Comment by luchenqian** [comment]
![34700fb4-f9b6-44a7-8b0f-577892430e2e](https://user-images.githubusercontent.com/22693832/59756517-766ef180-92bc-11e9-8a6d-ab2889c0f224.gif)

**Comment by mochixuan** [comment]
是不是用了scrollview，你看我demo里面有不同场景。

**Comment by luchenqian** [comment]
没有加scrollview

**Comment by luchenqian** [comment]
看了你的demo没啥区别

**Comment by mochixuan** [comment]
应该是参数了少了，demo里的代码也没几行，你可以对着demo改。
