### ISSUE TITLE
how to support auto scroll when you drag an item to the bottom of the list 

### ISSUE THREAD

**Issue by AlanWen2016** [mochixuan/react-native-drag-sort#141]
![image](https://user-images.githubusercontent.com/20939866/140850374-287404a9-a4fa-4649-b369-c08a2f357622.png)

**Comment by mochixuan** [comment]
https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/AutomaticSlidingOnePage.js

You should use this
