### ISSUE TITLE
I don't know how to make onDataChange works in the call back works in the hook

### ISSUE THREAD

**Issue by JonathanSum** [mochixuan/react-native-drag-sort#144]
我要以hook 來用,但你的repo好像只能用class comploment, 那是因為我不知道ondatachange 的call back 如何用在hook中.有用hook的example嗎?
thx.

**Comment by JonathanSum** [comment]
ERROR  TypeError: Cannot read property 'startTouch' of null, js engine: hermes

                onDataChange={(data, callback) => {
                    setItems(data)
                    React.useEffect(() => {
                        callback()
                    }, [data]);
                    // setState({ items: data }, () => {
                    //     callback()
                    // })
                }}

**Comment by JonathanSum** [comment]
我錯了,你的repo是完美的

**Comment by mochixuan** [comment]
ondatachange 里通过useState改变你的数据就可以了。如果是redux就通过相应方法改动就可以了。
