### ISSUE TITLE
标注一下行内子Touch事件用法吧，容易上手一点

### ISSUE THREAD

**Issue by chenyexuan** [mochixuan/react-native-drag-sort#147]
现在的拖动子项是用一个Touch事件包裹起来的，当Touch事件里再包裹更小的Touch事件，会触发最里面的Touch事件，而不会触发外层的Touch事件，就不会触发拖动功能了，要用ref获取拖动框主动调用绑定拖动框的拖动事件，之前没看里面的实现没发现，希望在使用文档上有说明

**Comment by mochixuan** [comment]
好的，谢谢提醒
