### ISSUE TITLE
Request for adaptive grid (height)

### ISSUE THREAD

**Issue by ElihuJ** [mochixuan/react-native-drag-sort#148]
Hi,
Thanks for developing such good package,
I have one request, when using AnySizeDragSortableView let's assume the following:
<img width="416" alt="Grid" src="https://user-images.githubusercontent.com/30395400/164157118-2d4c0954-747b-4c3b-9417-9921b4a9a54c.png">

I want to be able to move box 4 below 2 without causing 3 to move
So in summary it would be the same responsiveness that already exists for width size but to have the same for the height of the object as well

**Comment by mochixuan** [comment]
I understand your function, but the design of this component cannot implement this function now, sorry.
