### ISSUE TITLE
能否支持传入唯一key值，以保证数据变动后图片不会闪动，提高体验

### ISSUE THREAD

**Issue by yangbo5207** [mochixuan/react-native-drag-sort#17]
看了一下你的源码，里面用了index 作为key值，但是index并不能唯一标识某个组件，因此拖动之后，index改变，组件就会被重新渲染，而导致图片会闪动一下

所以是否能够支持自定义key值，如FlatList 组件的keyExtractor

这样就不会再index改变之后，而重新渲染组件了

**Comment by mochixuan** [comment]
谢谢建议，我看看如果有改进，待会加上这个，属性，谢谢建议。

**Comment by mochixuan** [comment]
已添加，删除带图片item时效果明显。
