### ISSUE TITLE
安卓真机拖拽会卡，附视频

### ISSUE THREAD

**Issue by codecomeon** [mochixuan/react-native-drag-sort#19]
试过安卓模拟器、ios模拟机、ios真机，情况都不错。只有安卓真机存在问题。

附：
视频和手机型号截图
https://pan.baidu.com/s/1gkxiOAwL-D5CtG0eHYmc4Q

**Comment by mochixuan** [comment]
首先非常感谢你把测试后的视频上传到云盘给我参考。
对于你的问题: 我的结论是手机可能比较卡顿，debug模式下RN动画会比较卡顿。
1. ios和ios模拟器是测试动画时性能是远远好于安卓的。
2. 插件代码都是js代码，不大可能出现兼容问题。
我打了一个安卓release包你可以测试一下如果还卡顿的话，你可以测试下网上其他开源类似的组件安卓在debug时的情况，如果不卡顿，肯定是我的优化没做好。
下载地址：https://fir.im/dragsort
期待你的反馈。
