### ISSUE TITLE
childrenHeight set auto size

### ISSUE THREAD

**Issue by gurbela** [mochixuan/react-native-drag-sort#21]
childrenHeight has fixed size, this is a problem for a custom size items.

**Comment by mochixuan** [comment]
The scene of this plugin is when the height of the item is already known. The scene is in the picture.

**Comment by hannanstd** [comment]
hi
i tested all of RN Sortable Package and realy your package is best. becasue works smoothly and doesnt affects to item sub state and it is very good.
but unfortunately is has a big problem that is width and height is constant. usually we need flexible height. ie: i use text input in dragable row and it has multiline props. and textInput height is variable when user type more than one line. please fix it.

**Comment by mochixuan** [comment]
The scene of this plugin is in the gif demo, you mentioned the function, and I will have time to study it later.

**Comment by ianmartorell** [comment]
I’m also really interested in adding variable height support to this plugin, I’m looking at the code right now to see if I could do it myself, maybe you can give me some pointers? Thanks

**Comment by mochixuan** [comment]
> I’m also really interested in adding variable height support to this package, I’m looking at the code right now to see if I could do it myself, maybe you can give me some pointers? Thanks

The left and top used here are to fix the position. So height and width are more important. If it consumes performance to calculate the width and height of each one, this function is not easy to do temporarily. You can try to use the flex layout, so that you don’t need to set a fixed width and height, and the animation can use useNativeDriver so that the performance will be greatly improved

**Comment by Svarto** [comment]
@ianmartorell could you share your solution? I am also looking to do this and would be great to know where to start

**Comment by ianmartorell** [comment]
@Svarto sure! Here's the component: https://gist.github.com/ianmartorell/c03c8127a83e638e29dbf3d58ef40744
