### ISSUE TITLE
it is need to hold long. how to can decrease press time?

### ISSUE THREAD

**Issue by hannanstd** [mochixuan/react-native-drag-sort#22]
Hi
your package is grateful. thanks. but it is need to hold long. how to can decrease time press time?
please add a "delayLongPress" props to handle longpress time.

**Comment by mochixuan** [comment]
This Component has only one file. The previous monitor used to press the time to trigger the event, but the React-Native touch is buggy. Now it is a long press scheme, which is very good. You can change the trigger time if you have a need. this.startTouch(index)
![企业微信截图_a5a80d96-3438-4e06-82eb-2e70d8116b39](https://user-images.githubusercontent.com/15728691/61679213-198dad80-ad38-11e9-8839-ecc82a8522cc.png)

**Comment by mochixuan** [comment]
Please wait, I will look at this delayLongPress property, if necessary, I will add it now.

**Comment by mochixuan** [comment]
Has added the property delayLongPress in v1.3.2

**Comment by hannanstd** [comment]
thanks man. be good luck.

**Comment by Gaganrana92** [comment]
You can give delayLongPress={200} to the Touchable Component of the render method of your AnySizeDragSortableView
