### ISSUE TITLE
数据多的话,拖动到屏幕边缘,不能拖到下一屏了,不知大佬有没有解决办法

### ISSUE THREAD

**Issue by yangwei2011** [mochixuan/react-native-drag-sort#23]

**Comment by mochixuan** [comment]
下一屏是什么意思？如果是向下的话，得配合ScrollView实现自动滑动。

**Comment by yangwei2011** [comment]
向下拖拽到边缘,希望ScrollView能够自动滚动,目前我就卡在这里....

**Comment by mochixuan** [comment]
对，😊就是这样的，要优化下，现在是不能，得自己实现，滑倒底部时再向下滑动，在2.0里再加。你可以参考react-native-sortable-listview它可以滑倒，如果是一行一个可以改用react-native-sortable-listview。或者按照它的方式实现。我有时间会研究一下

**Comment by yangwei2011** [comment]
期待哦~
