### ISSUE TITLE
发现个问题，拖动后，每个item之间距离很大

### ISSUE THREAD

**Issue by FTD-ZF** [mochixuan/react-native-drag-sort#26]
<DragSortableView
                        // dataSource={menuStore.firstData}
                        dataSource={this.state.firstData}
                        parentWidth={parentWidth}

                        childrenWidth={childrenWidth}
                        childrenHeight={childrenHeight}

                        scaleStatus={'scaleY'}

                        onDragStart={(startIndex, endIndex) => {
                            this.setState({
                                scrollEnabled: false
                            })
                        }}
                        onDragEnd={(startIndex) => {
                            this.setState({
                                scrollEnabled: true
                            })
                        }}
                        onDataChange={(data) => {
                            // if (data.length != menuStore.firstData.length) {
                            //     menuStore.firstData = data;
                            //     this.setState({});
                            //     // this.setState({
                            //     //     data: data
                            //     // })
                            // }
                            this._changeMoveData(data);

                        }}
                        keyExtractor={(item, index) => item.txt} // FlatList作用一样，优化
                        onClickItem={(data, item, index) => {

                        }}
                        renderItem={(item, index) => {
                            return this.renderDeleteItem(item, index)
                        }}
                    />

拖动前后产生的变化

![Simulator Screen Shot - iPhone XS Max - 2019-07-29 at 16 30 44](https://user-images.githubusercontent.com/20273784/62033453-8d3f2700-b21e-11e9-9350-3aeb0d510709.png)
![Simulator Screen Shot - iPhone XS Max - 2019-07-29 at 16 30 56](https://user-images.githubusercontent.com/20273784/62033469-97f9bc00-b21e-11e9-815c-818ac2e64040.png)

**Comment by FTD-ZF** [comment]
长按拖动超过一个item的距离，就会发生这个问题

**Comment by mochixuan** [comment]
没懂你的意思，你可以看看demo里的这个样式，或者测试下Demo,这种流失几乎不太可能，里面有两个逻辑进行复位，不会出现这种情况。https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/OneRowsPage.js

**Comment by FTD-ZF** [comment]
我把demo 传上来了 https://github.com/FTD-ZF/ReactNativeMobxFrame

**Comment by mochixuan** [comment]
你的这个方法出问题，不知道你的keyExtractor是哪里来的，但不是这么写的
_keyExtractor = (item, index) => {
        // _keyExtractor 返回的是唯一值，尽量不要用index
        return item.name; // 我的
        
        // 下面是你的，没看，应该有问题
        const { keyExtractor } = this.props;
        if (keyExtractor) {
            return keyExtractor(item, index);
        }
        return index.toString();
    };

**Comment by FTD-ZF** [comment]
谢谢，问题解决了，原来是字段名没对上啊， keyExtractor={(item, index) => item.txt} ===keyExtractor={(item, index) => item.name} ；

**Comment by mochixuan** [comment]
没事 !
