### ISSUE TITLE
期望可以控制中间某个子条目不被拖动变换位置，而不是只能开始的几个子条目固定

### ISSUE THREAD

**Issue by zhouzeyuuser** [mochixuan/react-native-drag-sort#27]
是否在接下来的版本考虑做子条目尺寸存在不同大小

**Comment by mochixuan** [comment]
中间几个不动，那上下两块怎么拖动呢，一拖动中间就会被移动了，你的项目需求有这个吗

**Comment by zhouzeyuuser** [comment]
我项目所期待的是在类似于网格布局中，并不是只有开始的条目固定，可能是随机的某一块固定。

**Comment by mochixuan** [comment]
有个问题就是，假设一排四个一共16个4排4列，假设固定了中间8个那第一个拖到最后一个时，逻辑得大改动
