### ISSUE TITLE
How to stop the event from bubbling

### ISSUE THREAD

**Issue by wowtrxqn** [mochixuan/react-native-drag-sort#30]
drag-sort Component is nested inside the ParallaxScrollView.

How to ensure that the sliding of ParallaxScrollView is not triggered when dragging internal drag components

**Comment by mochixuan** [comment]
ParallaxScrollView is also a ScrollView inside, you can refer to the ScrollView processing.

**Comment by wowtrxqn** [comment]
> ParallaxScrollView is also a ScrollView inside, you can refer to the ScrollView processing.

I will explore it myself, thank you for pointing.

**Comment by wowtrxqn** [comment]
![QQ图片20190909103105](https://user-images.githubusercontent.com/24369118/64499749-f3729b80-d2ec-11e9-83d5-404bc52a93fd.png)

**Comment by mochixuan** [comment]
ParallaxScrollView I downloaded and changed it before. I don't know if I see it and you are the same one. Before I saw it (View->View->ScrollView), you can expose the method and realize the communication between the father and the child.

**Comment by wowtrxqn** [comment]
> ParallaxScrollView I downloaded and changed it before. I don't know if I see it and you are the same one. Before I saw it (View->View->ScrollView), you can expose the method and realize the communication between the father and the child.

i used this，the same one we use？https://github.com/i6mi6/react-native-parallax-scroll-view

**Comment by mochixuan** [comment]
我可以说中文了: scrollEnabled属性你可以看下，其实是这样的，如果有scrollview的，它会优先获取触摸权限，但scrollEnabled={false} 就会放弃这个权限，其他组件就可以用了

**Comment by wowtrxqn** [comment]
> 我可以说中文了: scrollEnabled属性你可以看下，其实是这样的，如果有scrollview的，它会优先获取触摸权限，但scrollEnabled={false} 就会放弃这个权限，其他组件就可以用了

我再试试，谢谢老大

**Comment by mochixuan** [comment]
![企业微信截图_f8c5b068-40db-4c06-9573-5725f3979b4f](https://user-images.githubusercontent.com/15728691/64500670-ba3c2a80-d2f0-11e9-964c-0e2ac6a1d0b1.png)

**Comment by mochixuan** [comment]
再看看我demo，如果还是搞不定，我找个时间把写个demo。给你参考

**Comment by wowtrxqn** [comment]
> 再看看我demo，如果还是搞不定，我找个时间把写个demo。给你参考

我改好了，

> onDragStart={(startIndex,endIndex)=>{
                            homeAction.forbidden()
                            this.setState({
                                scrollEnabled: false
                            })
                        }}
                        onDragEnd={(startIndex)=>{
                            homeAction.allow()
                            this.setState({
                                scrollEnabled: true
                            })
                        }}

感觉有点怪，而且不流畅，debug很卡，最后松开后，还会自动删掉？

**Comment by mochixuan** [comment]
你可以看下我的demo,应该不会卡，在release里。

**Comment by wowtrxqn** [comment]
> 你可以看下我的demo,应该不会卡，在release里。

忘了回复了，不卡，效果可以，谢谢老大开源的插件，非常棒

**Comment by mochixuan** [comment]
没事，动画在debug模式性能非常低，这是RN的问题。
