### ISSUE TITLE
是否能够支持拖拽到parent区域之外，并且在onDragEnd时获得屏幕坐标X/Y呢？

### ISSUE THREAD

**Issue by wxsms** [mochixuan/react-native-drag-sort#31]
这样可以借助它实现一些排序以外的功能，参考微信发朋友圈的拖拽到底部删除，谢谢！

**Comment by mochixuan** [comment]
明白你要实现的功能: 这个组件只有一个JS文件，里面有个方法做了一下现在它的X,Y最大、最小值，你可以把那个最大Y值限制设置成屏幕高度就可以了。

**Comment by wxsms** [comment]
谢谢，请问是否接受这个 Feature 的 PR 呢？

意向加入 props：

1. `restrictDragEdge` Boolean, Default true
2. `onDragMove` Function

同时为 `onDragMove` 与 `onDragEnd ` 增加一个回调参数 `nativeEvent`，便于开发者获取屏幕坐标等信息。

**Comment by mochixuan** [comment]
1. react-native-drag-sort这个组件只有一个文件，你可以直接复制到你的项目里对源码进行修改。
2. 你说的这个两个需求都很简单，我可以给你说下怎么改，改哪里，但我觉得这两个功能不太适合这个组件，我就不加了😊。
代码 112和113： 你可以把他的限制改成你需要的大小或者直接删除了就可以完成你的需求1
onDragMove监听可以加在130行，x,y就是你想要的坐标了。

**Comment by wxsms** [comment]
好的。再次感谢。
