### ISSUE TITLE
componentWillReceiveProps & componentWillMount are deprecated and will be removed

### ISSUE THREAD

**Issue by Martian2Lee** [mochixuan/react-native-drag-sort#32]
Hi @mochixuan , great library and thanks for sharing! Any plans to update the deprecated methods?

Regards.

**Comment by mochixuan** [comment]
This lifecycle issue will be cancelled after 17th, but some users may have a version of React lower than 16. If they are afraid of their inability to use, wait until React is 17 and then modify it.
