### ISSUE TITLE
Bug: drag and drop overlapping 

### ISSUE THREAD

**Issue by ghasemikasra39** [mochixuan/react-native-drag-sort#36]
### Environment
```
React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 621.44 MB / 11.63 GB
      Shell: 5.4.2 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.19.0 - /usr/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
```
### What is the problem ?
![image](https://user-images.githubusercontent.com/24314029/66269407-e944ae00-e854-11e9-99bf-2ef8c5f04f67.png)

The same problem occurs in my own app with custom data.

**Comment by mochixuan** [comment]
The debug mode will compare the cards, you can see if this problem should not occur under the release, this is because the React-Native animation compares the cards in debug mode.

**Comment by mochixuan** [comment]
I will optimize the debug mode and I won't be stuck.

**Comment by mochixuan** [comment]
Sorry, there is a bug in the addition of NonScrollPage that is now fixed. You can download the demo to run again.

**Comment by ghasemikasra39** [comment]
> Sorry, there is a bug in the addition of NonScrollPage that is now fixed. You can download the demo to run again.

I have downloaded the app again. However, I am facing the same issue:
![image](https://user-images.githubusercontent.com/24314029/66371691-c4654d80-e9b0-11e9-941a-9c460d654b4a.png)
![image](https://user-images.githubusercontent.com/24314029/66371695-c92a0180-e9b0-11e9-96c3-821993c62d55.png)

**Comment by mochixuan** [comment]
Sorry, I didn't pack it, I am repacking it now, the code is up to date, you can run

**Comment by mochixuan** [comment]
You can try downloading the demo again.
