### ISSUE TITLE
Sortable = {false} does not prevent DragSortableView from dragging

### ISSUE THREAD

**Issue by neetrath** [mochixuan/react-native-drag-sort#4]
Sortable = {false} does not prevent DragSortableView from dragging

<DragSortableView
                    sortable={false}
                    dataSource={this.state.appList}
                    parentWidth={parentWidth}
                    childrenWidth={childrenWidth}
                    childrenHeight={childrenHeight}
                    marginChildrenRight={marginChildrenRight}
                    marginChildrenLeft={marginChildrenLeft}
                    marginChildrenTop={marginChildrenTop}
                    marginChildrenBottom={marginChildrenBottom}
                    onClickItem={(data, item, index) => { this._onPressItem(item) }}
                    renderItem={(item, index) =>
                        <View style={{ width: childrenWidth, height: childrenHeight }}>
                            <AppListItemView
                                data={item}
                                index={index}
                            />
                        </View>
                    }
                />

"dependencies": {
		"native-base": "^2.2.1",
		"react": "^16.0.0-alpha.12",
		"react-dom": "^15.6.1",
		"react-native": "0.52.0",
		"react-native-base64": "0.0.2",
		"react-native-cached-image": "^1.4.3",
		"react-native-check-box": "^2.1.6",
		"react-native-device-info": "^0.22.2",
		"react-native-dialog": "^5.1.0",
		"react-native-doc-viewer": "^2.7.8",
		"react-native-drag-sort": "^1.0.2",
		"react-native-fingerprint-scanner": "^2.5.0",
		"react-native-firebase": "4.3.0",
		"react-native-keyboard-aware-scroll-view": "^0.3.0",
		"react-native-keyboard-listener": "^1.1.0",
		"react-native-keychain": "^1.2.1",
		"react-native-modal": "^6.5.0",
		"react-native-modal-popover": "0.0.10",
		"react-native-navigation": "1.1.483",
		"react-native-permissions": "^1.1.1",
		"react-native-segmented-control-tab": "^3.3.1",
		"react-native-version-number": "^0.3.4",
		"react-navigation": "^1.0.0-beta.11",
		"sprintf-js": "^1.1.1",
		"string": "^3.3.3"
	},

**Comment by mochixuan** [comment]
Sorry, I have modified it.

> Sortable = {false} does not prevent DragSortableView from dragging
> 
> <DragSortableView
> sortable={false}
> dataSource={this.state.appList}
> parentWidth={parentWidth}
> childrenWidth={childrenWidth}
> childrenHeight={childrenHeight}
> marginChildrenRight={marginChildrenRight}
> marginChildrenLeft={marginChildrenLeft}
> marginChildrenTop={marginChildrenTop}
> marginChildrenBottom={marginChildrenBottom}
> onClickItem={(data, item, index) => { this._onPressItem(item) }}
> renderItem={(item, index) =>
> <View style={{ width: childrenWidth, height: childrenHeight }}>
> 
> 
> }
> />
> 
> "dependencies": {
> "native-base": "^2.2.1",
> "react": "^16.0.0-alpha.12",
> "react-dom": "^15.6.1",
> "react-native": "0.52.0",
> "react-native-base64": "0.0.2",
> "react-native-cached-image": "^1.4.3",
> "react-native-check-box": "^2.1.6",
> "react-native-device-info": "^0.22.2",
> "react-native-dialog": "^5.1.0",
> "react-native-doc-viewer": "^2.7.8",
> "react-native-drag-sort": "^1.0.2",
> "react-native-fingerprint-scanner": "^2.5.0",
> "react-native-firebase": "4.3.0",
> "react-native-keyboard-aware-scroll-view": "^0.3.0",
> "react-native-keyboard-listener": "^1.1.0",
> "react-native-keychain": "^1.2.1",
> "react-native-modal": "^6.5.0",
> "react-native-modal-popover": "0.0.10",
> "react-native-navigation": "1.1.483",
> "react-native-permissions": "^1.1.1",
> "react-native-segmented-control-tab": "^3.3.1",
> "react-native-version-number": "^0.3.4",
> "react-navigation": "^1.0.0-beta.11",
> "sprintf-js": "^1.1.1",
> "string": "^3.3.3"
> },

Sorry, I have modified it.
