### ISSUE TITLE
Support : drag while scrolling 

### ISSUE THREAD

**Issue by ghasemikasra39** [mochixuan/react-native-drag-sort#40]
The items that are rendered don't fit into one view, so I put the `DragSortableView` inside a `ScrollView`. However, when I drag one item, pulling it down (in order to see other items), the page doesn't scroll. 

```
React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 1.06 GB / 11.63 GB
      Shell: 5.4.2 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.19.1 - /usr/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.8 => 0.59.10
      "react-native-drag-sort": "^1.3.4",
```

**Comment by Arminhosseini** [comment]
I have this issue too.

**Comment by mochixuan** [comment]
You can check out a solution in my demo. [ScrollView](https://github.com/mochixuan/react-native-drag-sort/blob/f927c1fe9800b1de8821ccd316c770c4345f9baf/Example/app/container/ScrollPage.js#L35)

**Comment by aliassar** [comment]
Nice Idea. But can you make the item be dragged to another part of scrollview for bigger items? (e.g. end of scroll)

**Comment by mochixuan** [comment]
> Nice Idea. But can you make the item be dragged to another part of scrollview for bigger items? (e.g. end of scroll)

You can take a look at the demo, the functions that Demo implements, you can, if you don't realize it, you have to find your own way.
