### ISSUE TITLE
Inverted list - like in FlatList

### ISSUE THREAD

**Issue by durdevic** [mochixuan/react-native-drag-sort#42]
Would be nice to have an inverted list, I have a use case where I want to display the first element on the bottom of the screen so you can reach it easier. 

Otherwise awesome library! 

Thanks! 💪

**Comment by mochixuan** [comment]
In fact, you can reverse the data, and then you can restore it after sorting.

**Comment by durdevic** [comment]
I get your point, but what I actually meant was **like a chat in WhatsApp**, that the latest message is shown on the bottom and when a new comes in it shows bottom first. 

To see the older messages you would need to scroll upward. 

Would that be possible?
