### ISSUE TITLE
Prefer props over library globals 

### ISSUE THREAD

**Issue by andryak** [mochixuan/react-native-drag-sort#46]
The library defines a few globals including `maxScale`, `minOpacity`, `scaleDuration` and `slideDuration`. 

It would be nice if the user could alter these values (e.g., setting maxScale to 1 to disable item scaling).

Please consider merging in MR #45 which removes such globals and replaces them with props with the same defaults. Since all these props are optional and their default values match the ones assigned to the globals we can guarantee backwards compatibility (thus the minor version bump).

**Comment by mochixuan** [comment]
I thought that users might not use these properties, so I wrote a fixed one and added it to props now. Thank you.
