### ISSUE TITLE
support different children item size

### ISSUE THREAD

**Issue by aliassar** [mochixuan/react-native-drag-sort#47]
Hi, I really like this module due to high quality of implementation and I thought it would be good if working with different children item size was supported. You can see the exact meaning of my **feature** suggestion in the example below : 
![Untitled-1](https://user-images.githubusercontent.com/40848213/68375804-bf84ec80-015c-11ea-90c2-9357ddfa5031.png)

Since there is just one children item size for the whole draggable module and you determine the number of each view on a row based on that, this is what happening now : 
![Untitled-2](https://user-images.githubusercontent.com/40848213/68376044-2a362800-015d-11ea-956a-3fca14cd8a68.png)

Thank you

**Comment by mochixuan** [comment]
Thank you very much for your proposal. Several people have already proposed it. When time is sufficient, I will try out an adaptive version.

**Comment by aliassar** [comment]
I'll really appreciate that. Anyway thank you for quick answer.

**Comment by mochixuan** [comment]
Adaptive size has been developed and drag can be triggered anywhere
