### ISSUE TITLE
dragging simultaneously with scrollview

### ISSUE THREAD

**Issue by aliassar** [mochixuan/react-native-drag-sort#48]
Hi, Since I found your module useful for everyone, I think it will be awesome if we can drag simultaneously with scrollview. I can show you what I think below (I made it with movie editing tools) :
![Android-Emulator-Nexus_One_API_23_5554-2019-11-07-13-14-22_2](https://user-images.githubusercontent.com/40848213/68382261-98341c80-0168-11ea-8345-8369d191ad48.gif)
And this feature isn't there yet:
![Android-Emulator-Nexus_One_API_23_5554-2019-11-07-13-14-22](https://user-images.githubusercontent.com/40848213/68382406-e3e6c600-0168-11ea-879d-0c1e1f7c9ea6.gif)

Thanks for the hard works

**Comment by mochixuan** [comment]
React-Native sliding processing is more complicated. I have time to try to implement this feature. Thanks for your advice.

**Comment by aliassar** [comment]
Well, thanks for your works. If you found any relevant resource or need help in this case , involve me please.

**Comment by mochixuan** [comment]
Just found a problem and your animation may have problems. Your arrow is the answer, but how can the hand automatically go up when it is automatically swiped?
