### ISSUE TITLE
Can't run example app

### ISSUE THREAD

**Issue by feliperaul** [mochixuan/react-native-drag-sort#49]
This lib looks awesome, but I spent more than 2 hours trying to make it run after git cloning it and nothing.

Can you please provide instructions of how we're able to run it?

**Comment by mochixuan** [comment]
In the example is a complete project, you can directly run the React-Native project.

**Comment by ds-karpov** [comment]
I have the same problem. I clone your repo, make npm install in Example folder. Then try to install Pods, but I have not it in ios folder. Also react-native run-ios return error "Unrecognized command ".
Could you please add more details instruction?

**Comment by mochixuan** [comment]
Sorry, my Example may be different from other people's. Example is https://github.com/mochixuan/react-native-drag-sort/tree/master/Example. No need for npm i react-native-drag-sort. The code is already inside

**Comment by ds-karpov** [comment]
> Sorry, my Example may be different from other people's. Example is https://github.com/mochixuan/react-native-drag-sort/tree/master/Example. No need for npm i react-native-drag-sort. The code is already inside

Dear mochixuan,

Could you please write commands queue?
I do next -> 
git clone
cd react-native-drag-sort/Example
npm install
npm start
npx react-native run-ios - return "Could not find iPhone 6 simulator"

I have tried build it directly through Xcode. -> 
![image](https://user-images.githubusercontent.com/64860559/90529755-bcec0480-e17c-11ea-8b4f-a13e15b7b5f6.png)

Xcode return the next error 
![image](https://user-images.githubusercontent.com/64860559/90531235-7d261c80-e17e-11ea-8ec9-d61f41d42fba.png)

**Comment by mochixuan** [comment]
> > Sorry, my Example may be different from other people's. Example is https://github.com/mochixuan/react-native-drag-sort/tree/master/Example. No need for npm i react-native-drag-sort. The code is already inside
> 
> Dear mochixuan,
> 
> Could you please write commands queue?
> I do next ->
> git clone
> cd react-native-drag-sort/Example
> npm install
> npm start
> npx react-native run-ios - return "Could not find iPhone 6 simulator"
> 
> I have tried build it directly through Xcode. ->
> ![image](https://user-images.githubusercontent.com/64860559/90529755-bcec0480-e17c-11ea-8b4f-a13e15b7b5f6.png)
> 
> Xcode return the next error
> ![image](https://user-images.githubusercontent.com/64860559/90531235-7d261c80-e17e-11ea-8ec9-d61f41d42fba.png)

You can query error in the search engine, for example: double-conversion. You can query the results.
