### ISSUE TITLE
Scroll the view when drag item to the top or bottom of screen

### ISSUE THREAD

**Issue by kevtran410** [mochixuan/react-native-drag-sort#5]
How can auto scroll down or up ScrollView when drag item to the bottom or top of screen?

**Comment by robynluo** [comment]
@mochixuan I have the same question for you also, can you fix this issue?

**Comment by Gaganrana92** [comment]
Remove/ comment this condition from the startAutoScroll() method of the AnySizeDragSortableView.js file.
 
 // Anti-shake 1.x1
             if (!this.curScrollData.hasScroll) {
               return;
            }
