### ISSUE TITLE
Plans to deprecate componentWillReceiveProps & WillMount?

### ISSUE THREAD

**Issue by lsps9150414** [mochixuan/react-native-drag-sort#53]
First of all, thank you very much for the awesome work! This is the most sophisticated one of the kind I have found.

I am using this in a project with a newer react-native version so I am seeing the orange warning box that says `componentWillReceiveProps/componentWillMount has been renamed, and is not recommended for use`.

I would like to know if you have any plan to refactor this recently, or if you would take PR for this? Thanks!

**Comment by mochixuan** [comment]
Thank you very much for your suggestion, I have removed these two methods in the latest version.

**Comment by lsps9150414** [comment]
Thank you so much for the fast response!!
