### ISSUE TITLE
列表拖动有点卡，iOS CPU上涨

### ISSUE THREAD

**Issue by monkeyxdd** [mochixuan/react-native-drag-sort#55]
<ScrollView
            ref={scrollView => (this.scrollView = scrollView)}
            scrollEnabled={scrollEnabled}
            style={styles.container}>
            <DraggableFlatList
              dataSource={fundData.slice()}
              parentWidth={parentWidth}
              childrenWidth={childrenWidth}
              childrenHeight={childrenHeight}
              scaleStatus={'scaleY'}
              onDragStart={(startIndex, endIndex) => {
                model.setScrollEnable(false)
              }}
              onDragEnd={startIndex => {
                model.setScrollEnable(true)
              }}
              onDataChange={data => {
                if (data.length !== fundData.length) {
                  model.resetData(data)
                }
              }}
              keyExtractor={(item, index) => item.name}
              onClickItem={(data, item, index) => {}}
              renderItem={(item, index) => {
                return this.renderItem(item, index)
              }}
            />
          </ScrollView>

**Comment by mochixuan** [comment]
你可以看看我的Example，里面有很多场景。你用的应该是非自动滑动，更不可能卡顿了。
