### ISSUE TITLE
这个组件可以实现单行水平拖动吗

### ISSUE THREAD

**Issue by HeMa321** [mochixuan/react-native-drag-sort#57]
请教下,horizontal=true的时候,实现拖拽更改item,需要怎么样进行修改?多谢

**Comment by mochixuan** [comment]
我这个暂时没有横向滑动的功能。要改下组件才行。如果不需要滑动的话可以直接用

**Comment by HeMa321** [comment]
是需要横向滑动的，不行的话我再看看逻辑修改或找找其他的，多谢------------------ 原始邮件 ------------------
发件人: "mochixuan"<notifications@github.com>
发送时间: 2020年3月14日(星期六) 上午10:53
收件人: "mochixuan/react-native-drag-sort"<react-native-drag-sort@noreply.github.com>;
抄送: "HeMa321"<735847599@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mochixuan/react-native-drag-sort] 这个组件可以实现单行水平拖动吗 (#57)




 
我这个暂时没有横向滑动的功能。要改下组&#x4EF6;才行。如果不需要滑动的话可以直接用
 
&mdash;

**Comment by mochixuan** [comment]
没有试过，你可以改下代码，很好改的

**Comment by HeMa321** [comment]
可以的  已经修改好了 ,多谢提供🙏
