### ISSUE TITLE
无法拖动

### ISSUE THREAD

**Issue by explorefit** [mochixuan/react-native-drag-sort#61]
请问无法拖动，按照例子写的，

**Comment by mochixuan** [comment]
是不是在ScrollView里面，或者设置了sortable。另外触发是长按触发。

**Comment by explorefit** [comment]
import { DragSortableView,AutoDragSortableView } from 'react-native-drag-sort'
<AutoDragSortableView
                dataSource={groupList}
                parentWidth={ parentWidth }
                childrenWidth={childrenWidth}
                childrenHeight={ childrenHeight}
                onDragStart={
                  (startIndex, endIndex) => {
                    this.setState({
                      scrollEnabled: false
                    })
                  }
                }
                onDragEnd={
                  (startIndex) => {
                    this.setState({
                      scrollEnabled: true
                    })
                  }
                }
                onDataChange={
                  (groupList) => {
                    // delete or add data to refresh
                    if (data.length != this.state.data.length) {
                      this.setState({
                        groupList: groupList
                      })
                    }
                  }}
                onClickItem={(data, item, index) => {
                  // click delete
                  // if (this.state.isEnterEdit) {
                  //     const newData = [...data]
                  //     newData.splice(index,1)
                  //     this.setState({
                  //         data: newData
                  //     })
                  // }
                }}
                keyExtractor={(item, index) => item.id}
                renderItem={(item, index) => {
                  return this.renderItem(item, index)
                }}
              />
直接这样写的，长按没反应，麻烦看一下，谢谢你了

**Comment by mochixuan** [comment]
DragSortableView不实现自动滑动。AutoDragSortableView 有自动滑动。如果你不需要自动滑动可以把AutoDragSortableView改成DragSortableView。例子好像没有问题，最简单的方法是直接用我的例子改

**Comment by explorefit** [comment]
我用的你例子里面的代码，我没放到ScrollView里面，就是长按没反应

**Comment by mochixuan** [comment]
你可以看下这个https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/NonScrollPage.js
