### ISSUE TITLE
Any reason to copy the code to the example instead of use npm?

### ISSUE THREAD

**Issue by nelsonprsousa** [mochixuan/react-native-drag-sort#67]
Just noticed that on your example you do not used the library using npm, and instead copy pasted the code of the lib. Is there any reason for that that I am not aware of?

Thank you, nice job!

**Comment by mochixuan** [comment]
When I developed the library, I developed it in Example. After the development and testing, I copied it into the lib and passed npm publish. So you can use the ones in npm. Local is for development and use

**Comment by nelsonprsousa** [comment]
Okay, gonna give it a try during this week 🙏 

Thank you
