### ISSUE TITLE
AutomaticSlidingOnePage不会自动往下滚动

### ISSUE THREAD

**Issue by iOSQiao** [mochixuan/react-native-drag-sort#68]
AutomaticSlidingOnePage在超过屏幕高度后不会自动往下滚动。如果在数据加载后，数据超出屏幕的高度了，这时候没有去滚动列表，而是直接长按其中一个Item，往下拖动到列表底部，这时候列表不会自动往下滚动。如果在长按之前滚动了一下列表，这时候再去长按其中一个Item，往下拖动到列表底部，列表才会自动往下滚动。

这是一个bug吗？

**Comment by mochixuan** [comment]
最初设计的时候用作Tab排序用的，可能没有测试过加载数据的问题。这个问题我待会看下。

**Comment by mochixuan** [comment]
非常感觉你提出的这个问题。现在已经解决在最新的版本2.2.3

**Comment by iOSQiao** [comment]
向你学习。
