### ISSUE TITLE
AutomaticSlidingOnePage第一次长按拖动失效

### ISSUE THREAD

**Issue by iOSQiao** [mochixuan/react-native-drag-sort#69]
AutomaticSlidingOnePage刚加载完数据后，第一次长按其中一个Item，无法拖拽调整顺序。

还有第一次长按其中一个Item之后，onDragEnd事件会触发，而不是等到触摸手势松开后才触发的。这就影响了这个Item实现一些长按提示功能。

希望可以改进。

**Comment by mochixuan** [comment]
你是要的是我的DEMO吗？我这边完全没有问题。你可以看下我最新的DEMO

**Comment by iOSQiao** [comment]
我不是用的你的demo，我等下尝试一下

**Comment by iOSQiao** [comment]
git clone 不下来，我的用法是这样的

`
 <AutoDragSortableView
                            dataSource={this.state.data}
                            parentWidth={this.parentWidth}
                            childrenWidth={this.childrenWidth}
                            childrenHeight={this.childrenHeight}
                            keyExtractor={this._keyExtractor}
                            renderItem={this._renderItem}
                            delayLongPress={1000 * 0.5}
                            maxScale={1}
                            onDragStart={this._onDragStart}
                            onDragEnd={this._onDragEnd}
                            onDataChange={this._onDataChange}
                        />
`

这样子就会出现上面我说的情况。

**Comment by mochixuan** [comment]
参数都没有问题。你可以下载DEMO看下。没有人出现过这个问题。“无法拖拽调整顺序”没有出现过。

**Comment by iOSQiao** [comment]
我知道出现这个问题的情况了。

当Items超出屏幕之后，第一次长按拖拽就会出现上面的问题。

**Comment by mochixuan** [comment]
你能录制一个GIF或者给一个DEMO.apk我看下吗？我看看是什么情况，你说的这个问题我本地测试是没有的

**Comment by iOSQiao** [comment]
- 
![test](https://user-images.githubusercontent.com/13956756/87518226-9553d900-c6b2-11ea-9529-91816dd79e65.gif)

当我第一次长按的时候，深颜色闪了一下就不见了。这是因为onDragEnd响应了。

第二次长按的时候就完全正常了。

**Comment by iOSQiao** [comment]
![test1](https://user-images.githubusercontent.com/13956756/87518697-304cb300-c6b3-11ea-918b-7f82df614e13.gif)

Items没有超出屏幕的时候，第一次也是正常的。

**Comment by mochixuan** [comment]
知道原因了，是昨天改的那个问题造成的。我改下发一个包

**Comment by iOSQiao** [comment]
我还以为是我的使用问题呢，手动狗头^_^

**Comment by mochixuan** [comment]
给你造成不便非常抱歉，由于组件设计之初没有考虑到分页加载(第一次加载不满一页)，插件其实不滑动时也会自动检测高度。
现在已经解决了这个问题。可以看最新版2.2.4。测试完成了iphone和华为手机

**Comment by iOSQiao** [comment]
👍👍👍

**Comment by xclidongbo** [comment]
第一次长按拖动失败什么原因? 我也遇到了.

**Comment by mochixuan** [comment]
> 第一次长按拖动失败什么原因? 我也遇到了.

可以对着用例看下
