### ISSUE TITLE
Speed of AutoDragSortableView

### ISSUE THREAD

**Issue by nelsonprsousa** [mochixuan/react-native-drag-sort#72]
Hi,

I am testing this library and I am wondering if we can change the auto drag speed. Currently the speed is low for our needs and I couldn't find any prop that allow us to change the speed. Am I missing something?

P.S: I have one example, running react-native 0.63.1 (last version) and react-navigation 5.7.1 (last version). If you want I can open a pull request to change the example (is using react-native 0.56 and react-navigation 2.11.2).

**Comment by mochixuan** [comment]
### **props：**
autoThrottle: PropTypes.number;
autoThrottleDuration: PropTypes.number
### **example：**
autoThrottle: 3;
 autoThrottleDuration: 10
### **meaning：**
Slide 3 units every 10 seconds
