### ISSUE TITLE
Drag & drop ability interfering with tapping

### ISSUE THREAD

**Issue by annepham25** [mochixuan/react-native-drag-sort#73]
The elements that I am dragging, I would also like the functionality of being able to tap on them to view. However, my current implementation of tapping on them is conflicting with the libraries implementation of the long press to rearrange the items. Are there any ideas of how I can resolve this conflict?

**Comment by mochixuan** [comment]
onClickItem?: (data: any[],item: any,index: number) => void
You can use onClickItem attribute
