### ISSUE TITLE
Is is possible to do a "DragAddPage"?

### ISSUE THREAD

**Issue by nelsonprsousa** [mochixuan/react-native-drag-sort#74]
I was wondering if it is possible to use something similar to DragDeletePage, but instead of deleting an item, add an item.

For example, instead of having a delete button at the bottom, we could have an "Add button" and drag it to the FlatList.

Is it possible / doable?

**Comment by mochixuan** [comment]
can be realised

**Comment by nelsonprsousa** [comment]
@mochixuan any news on this?
