### ISSUE TITLE
抄ScrollFixedAddPage例子无法拖动

### ISSUE THREAD

**Issue by emclab** [mochixuan/react-native-drag-sort#75]
`react-native-drag-sort`是目前找到的唯一一个满足我需求的。Well done and thank you!

我按照ScrollFixedAddPage的例子，做了少许改动，和image picker一起用。把isEnterEdit去掉了。我希望实现的功能是：
    1. 用户可以左右和上下拖动调整图像的次序
    2. 可以click x to delete图像
    3. 3行排列。一排有3张图像。
   4. 最后一张是+

![Capture](https://user-images.githubusercontent.com/946013/88743644-04412100-d0fa-11ea-9f41-83d6269c9a77.JPG)

以下是code:

    const [scrollEnabled, setScrollEnabled] = useState(true);
    const parentWidth = screen_width - 18
    const marginChildrenTop = 7
    const marginChildrenBottom = 0
    const marginChildrenLeft = 0
    const marginChildrenRight = 7
    childrenWidth = parentWidth/3;
    childrenHeight = childrenWidth;

     const renderItem = (item,index) => {
         return (
            <View style={styles.item}>
                {/* <View style={styles.item_children}> */}
                    <FastImage
                        source={{uri:item.path}} 
                        resizeMode={FastImage.resizeMode.cover} 
                        key={index}
                        style={{
                            width:childrenWidth-1, 
                            height:childrenWidth-1, 
                            position:"absolute",
                            //verticalAlign:0,
                            //paddingTop:0,
                    
                        }}
                        />
                    
                {/* </View> */}
                <Image
                    style={styles.item_delete_icon}
                    source={require('../../../assets/image/clear.png')}
                />
            </View>
         )
      }

     return (
        <ScrollView
            ref={(scrollView) => scrollView = scrollView}
            scrollEnabled = {scrollEnabled}
            style={styles.container}>
            <View style={styles.sort}>
                <DragSortableView
                    dataSource={pics}
                    parentWidth={parentWidth}

                    childrenWidth= {childrenWidth}
                    childrenHeight={childrenHeight}

                    marginChildrenTop={marginChildrenTop}
                    marginChildrenBottom={marginChildrenBottom}
                    marginChildrenLeft={marginChildrenLeft}
                    marginChildrenRight={marginChildrenRight}

                    onDragStart={(startIndex,endIndex)=>{
                        setScrollEnabled(false);
                    }}
                    onDragEnd={(startIndex)=>{
                        setScrollEnabled(true);
                    }}
                    onDataChange = {(data)=>{
                        // delete or add data to refresh
                        updateImages(data);
                        
                        /* if (data.length != len) {
                            deleteImage(data);
                        } */
                    }}
                    onClickItem={(data,item,index)=>{
                        updateImages(data);

                    }}
                    keyExtractor={(item,index)=> item.id} // FlatList作用一样，优化
                    renderItem={(item,index)=>{
                        return renderItem(item,index)
                    }}
                />
                <View style={[
                    {
                        width: childrenWidth,
                        height: childrenHeight,
                        marginTop: marginChildrenTop,
                        marginLeft: marginChildrenLeft,
                        marginBottom: marginChildrenBottom,
                        marginRight: marginChildrenRight,
                        justifyContent: 'center',
                        alignItems: 'center'
                    },
                    len % 4 !== 0 ? {
                        position: 'absolute',
                        zIndex: 999,
                        top: parseInt(len / 4) * (childrenHeight + marginChildrenBottom + marginChildrenTop),
                        left: parseInt(len % 4) * (childrenWidth + marginChildrenLeft + marginChildrenRight)
                    } : {}
                ]}>
                    <TouchableOpacity 
                        style={styles.item_children} 
                        onPress={()=> {
                            helper.handleAddPicture(addImages, 'photo', false, null)
                        }}
                    >
                        <Text style={{fontSize: 24,color: '#000'}}>+</Text>
                    </TouchableOpacity>
                </View>
            </View>
        </ScrollView>
    )

    const style = StyleSheet.create({
     container: {
        flex: 1,
        paddingTop: 20,
    },
    sort: {
        marginLeft: 20,
    },
    item: {
        width: childrenWidth-10,
        height: childrenHeight-10,
    },
    item_children: {
        width: childrenWidth-8,
        height: childrenHeight-8,
        //backgroundColor: '#f2f2f2',
        backgroundColor:'#ffe6f7',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 4,
        marginTop: 8,

    },
    item_delete_icon: {
        //width: 3,
        //height: 3,
        position: 'absolute',
        right: 1,
        top: 1,
    },
    item_icon: {
        width: childrenWidth-4-8,
        height: childrenHeight-4-8,
        resizeMode: 'contain',
        position: 'absolute'
    },

现在的问题是无法拖动。另外图像只能排两行。另外，delete icon只能摆在左上角，background颜色无法改变。不知道哪里没有抄对。另外Doc里`Download Android Example`的连接不好用。谢谢。

**Comment by mochixuan** [comment]
1. 首先你的renderItem里的TouchableOpacity可以删除了。组件有监控点击的方法onClickItem={(data,item,index){}
2. scrollEnabled是没有问题目前看来，你把你的TouchableOpacity删除掉。改用属性onClickItem。

**Comment by emclab** [comment]
按建议作了如下改动。 把<TouchableOpacity>换成<View>。把`onPress`拿掉：

             <View style={styles.item_children}>             
                        <Text style={{fontSize: 24,color: '#000'}}>+</Text>
              </View>

然后把onClickItem改成：

          onClickItem={(data,item,index)=>{
                        helper.handleAddPicture(addImages, 'photo', false, null)
          }

改动后，拉动照片换位还是没有反应（在照片上点左鼠标键，然后拖动）。点击图像左上角的X会击发`onClickItem`运行从相册取照片。选照片后会出错：`[Error: User cancelled image selection]`. 改动前用TouchableOpacity运行选照片不会出错。

**Comment by mochixuan** [comment]
拖动是长按触发的。不是点击就拖动了。还有删除item后要改变data，把数据也删除了。你可以参考其他的几个

**Comment by emclab** [comment]
呃呃，很长按可以拉动。可以调节长按的时间吗？感觉按的时间比普通的长按长

**Comment by mochixuan** [comment]
delayLongPress: PropTypes.number,这个属性可以设置长按多久触发。
你可以使用真机试试，几乎不可能出现按动不触发的问题。除手机性能很差且开启了debug模式(debug模式动画性能很差，RN原因)。
