### ISSUE TITLE
为什么使用AutoDragSortableView/DragSortableView模拟器上运行，拖拽感觉卡卡的，位置还会不对

### ISSUE THREAD

**Issue by inkCrazy** [mochixuan/react-native-drag-sort#76]
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-drag-sort": "^2.2.1",

![image](https://user-images.githubusercontent.com/12253453/89374843-0d944400-d71f-11ea-95f3-529c5203796f.png)
![image](https://user-images.githubusercontent.com/12253453/89374952-40d6d300-d71f-11ea-94df-5a5191b0bc7d.png)
还有重叠的
![image](https://user-images.githubusercontent.com/12253453/89374996-564bfd00-d71f-11ea-99c0-63d3908046d4.png)

**Comment by mochixuan** [comment]
记得配置keyExtractor这个参数。
模拟器上性能原因RN会很卡。
而且debug模式release模式性能也差一大截。
你可以用性能很差的手机测试release包，不会出现卡顿现象的。
