### ISSUE TITLE
TypeError: null is not an object (evaluating 'this.touchCurItem.ref.setNativeProps')

### ISSUE THREAD

**Issue by yz1311** [mochixuan/react-native-drag-sort#77]
`TypeError: null is not an object (evaluating 'this.touchCurItem.ref.setNativeProps')`

[SortAndFixedPage.js](https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/SortAndFixedPage.js)

 使用的是最新版本的库，按照下面操作，<font color='red'>`必然`</font>出现报错:

1. 进入编辑模式
2. 删除一个tag
3. 长按刚才删除tag的右侧的第一个(必须是右侧且第一个)tag，立马报红

**Comment by mochixuan** [comment]
你好，按你的描述进入Example进行了测试，（一排4个，假设我删除的第二排的某个），之后我长按第二排最后一个就是第4个，没有出现报错。
根据报错信息this.touchCurItem.ref.setNativeProps只有两处调用，调用前都被判断了是否为空，非空判断到调用之间没有赋值逻辑，按理不肯能为空。
你说最新版本报错，是你以前用的老版本，直接更新了还是，直接用的最新版本，keyExtractor属性记得配置。
如果你跑demo会报错的话，能不能截取一个gif。或者具体描述下，是跑demo还是你的代码报错加上手机和型号

**Comment by yz1311** [comment]
@mochixuan 

我刚试了下，用demo中的0.56版本是没问题的，但是我目前用的是0.63.2版本，用0.63.2＋demo中的代码，就会出现这情况
这是gif
![](https://s31.aconvert.com/convert/p3r68-cdx67/9bz11-oymp8.gif)

**Comment by yz1311** [comment]
SortAndFixedPage  不管是从项目中还是npm包中引入 DragSortableView，均会报错，我现在再试下其他RN版本

**Comment by mochixuan** [comment]
你好我刚才测试了一下，最新版的RN直接复制的代码没有任何问题。

依赖包：

```
"dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-drag-sort": "^2.2.4"
  }
```

手机(MI 6)、系统(Android)
测试步骤：
1. 新建项目。
2. 复制SortAndFixedPage到app.js中。
3. 修改Image图片地址。
4. 切换线上地址import { DragSortableView} from 'react-native-drag-sort'
5. 测试。
结果：未出现标题所显示问题。

**Comment by yz1311** [comment]
@mochixuan 

我在android(真机)和ios(模拟器)都出现了问题,大概调试了一下

下面我删除demo中的`热点`标签(第三个，index=2),删除后，会调用_renderItemView，将触发`this.sortRefs.set(2,null)}`,然后长按后面的`NBA`标签(原来的index=3,现在的index=2)

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ghlkddrv3dj30hf0e0mzt.jpg)
![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ghlkcsd10pj30gy0ec0v9.jpg)

但是此时的sortRefs对象是

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ghlked29voj30gs0eadir.jpg)


--------

上面三张图是同一个断点打的，此时进入`startTouch`方法获取的ref就是null

**Comment by mochixuan** [comment]
你的图片加载不出来，你可以加我微信：把GIF发我吗？：wx1306894924

**Comment by apgsn** [comment]
Hi @mochixuan, is this fixed? Because I am having the same error and it's not clear from the translation (via google translate) if it's solved.

**Comment by yz1311** [comment]
@apgsn   try change the keyExtractor function to 

```
keyExtractor={(item, index) => item.text + '_' + index}
```

**Comment by mochixuan** [comment]
Please ensure that the keyExtractor is the unique identification code of the item, not an index that is easy to repeat.
good: keyExtractor={(item, index) => item.id}
bad: keyExtractor={(item, index) => index}

**Comment by mochixuan** [comment]
你好问题已经修复。
原因：
 react-native最新版的key不变时，ref方法不会被调用。
解决方案：
 修改ref的key和组件key一样。
最新版本2.3.4

**Comment by mochixuan** [comment]
> Hi @mochixuan, is this fixed? Because I am having the same error and it's not clear from the translation (via google translate) if it's solved.

Please use the latest version 2.3.4, the problem has been fixed, compatible with the latest version (react-native@0.63.2)

**Comment by apgsn** [comment]
I see, now it works properly. Thanks for the quick update, you're doing a great job.
