### ISSUE TITLE
null is not an object (evaluating 'this.scrollRef.scrollTo')

### ISSUE THREAD

**Issue by metahexane** [mochixuan/react-native-drag-sort#78]
I have the AutoDragSort containing items, which when pressed on open up a modal. There is no problem when the modal opens up, but when I close the modal, I get this error (line 574 of AutoDragSortableView). Any idea what the cause may be. The code is pretty complex so getting to an example might be tricky, but perhaps you could have an idea what the cause of the error might be?

Im on Expo SDK 38 (runs on RN 62.2) and on the latest version of this library.

**Comment by mochixuan** [comment]
What version are you using 2.2.4 or 2.3.4? You can use 2.3.4 for the latest version of RN.

**Comment by metahexane** [comment]
I was using 2.2.4. I upgraded to 2.3.4 before opening the issue, but the error persists.

**Comment by mochixuan** [comment]
2.3.4 Optimized compatibility with RN@0.62.3 for 2.2.4. Can you copy the error or take a screenshot, let me see where the problem is, and the wrong scene. Easy for me to simulate

**Comment by Bavithra** [comment]
Running coverage on untested files…/node_modules/react-native-drag-sort/AutoDragSortableView.
js:166
     ` _this.scrollRef.scrollTo({`
                      ^

TypeError: Cannot read property 'scrollTo' of null
    at AutoDragSortableView.scrollTo (/Users/bavithra.thangaraj/Documents/Temasak/core-mobile/node_modules/react-native-drag-sort/AutoDragSortableView.js:574:24)
    at Timeout._onTimeout (/node_modules/react-native-drag-sort/AutoDragSortableView.js:119:22)
    at listOnTimeout (internal/timers.js:549:17)``

**Comment by Bavithra** [comment]
Running coverage on untested files…/node_modules/react-native-drag-sort/AutoDragSortableView.
js:166
_this.scrollRef.scrollTo({
^

TypeError: Cannot read property 'scrollTo' of null
at AutoDragSortableView.scrollTo (node_modules/react-native-drag-sort/AutoDragSortableView.js:574:24)
at Timeout._onTimeout (/node_modules/react-native-drag-sort/AutoDragSortableView.js:119:22)
at listOnTimeout (internal/timers.js:549:17)``

**Comment by mochixuan** [comment]
Okay, if there is a problem, I will try to solve it today,

**Comment by mochixuan** [comment]
Hello, can I ask some questions?
premise:
There will be no problems with my test, and it can run on the latest version of RN.
problem:
1. Was your error triggered before the click triggered the drag, or was it triggered after the click?
2. You can print whether this.scrollRef property is empty in the componentDidMount function.
3. I want to confirm whether the ref is invalid due to the version, or scrollTo is removed.

**Comment by apgsn** [comment]
Hi @mochixuan, I'm having the same issue. Here are some details:
Versions: 
"react-native-drag-sort": "^2.3.4"
"react-native": "^0.63.2"

I'm using `AutoDragSortableView` to display, select and reorder some base64 images. This issue seems to happen when I have 20+ images, I scroll down, and then exit the view by navigating back to the previous screen. To do so I'm using a back button in a navbar, for the rest the screen has other components (eg. footer etc.), but they don't seem related to the problem, since I removed them all and the issue is still there.
I have no shareable code (because NDA), but I'll try to give you an example when I have some spare time to replicate the problem on my own.

The error seems to be non-blocking, although I noticed whenever I select a picture the scroll position goes back to the top. I'm currently investigating to figure out if it is my fault or the components'.

Error: 
![Simulator Screen Shot - iPhone 11 - 2020-08-19 at 11 09 01](https://user-images.githubusercontent.com/5557838/90615887-fcfac800-e20c-11ea-9762-da1ec3d2315b.png)

**Comment by mochixuan** [comment]
> Hi @mochixuan, I'm having the same issue. Here are some details:
> Versions:
> "react-native-drag-sort": "^2.3.4"
> "react-native": "^0.63.2"
> 
> I'm using `AutoDragSortableView` to display, select and reorder some base64 images. This issue seems to happen when I have 20+ images, I scroll down, and then exit the view by navigating back to the previous screen. To do so I'm using a back button in a navbar, for the rest the screen has other components (eg. footer etc.), but they don't seem related to the problem, since I removed them all and the issue is still there.
> I have no shareable code (because NDA), but I'll try to give you an example when I have some spare time to replicate the problem on my own.
> 
> The error seems to be non-blocking, although I noticed whenever I select a picture the scroll position goes back to the top. I'm currently investigating to figure out if it is my fault or the components'.
> 
> Error:
> ![Simulator Screen Shot - iPhone 11 - 2020-08-19 at 11 09 01](https://user-images.githubusercontent.com/5557838/90615887-fcfac800-e20c-11ea-9762-da1ec3d2315b.png)

I tested the latest version and it can run and interact normally. You can copy the page into your project for testing.
My dependency package
```
"dependencies": {
     "react": "16.13.1",
     "react-native": "0.63.2",
     "react-native-drag-sort": "^2.2.4"
   },
```
You can copy the code at the address below, and it works normally.
https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/AutomaticSlidingThreePage.js

**Comment by mochixuan** [comment]
> Hi @mochixuan, I'm having the same issue. Here are some details:
> Versions:
> "react-native-drag-sort": "^2.3.4"
> "react-native": "^0.63.2"
> 
> I'm using `AutoDragSortableView` to display, select and reorder some base64 images. This issue seems to happen when I have 20+ images, I scroll down, and then exit the view by navigating back to the previous screen. To do so I'm using a back button in a navbar, for the rest the screen has other components (eg. footer etc.), but they don't seem related to the problem, since I removed them all and the issue is still there.
> I have no shareable code (because NDA), but I'll try to give you an example when I have some spare time to replicate the problem on my own.
> 
> The error seems to be non-blocking, although I noticed whenever I select a picture the scroll position goes back to the top. I'm currently investigating to figure out if it is my fault or the components'.
> 
> Error:
> ![Simulator Screen Shot - iPhone 11 - 2020-08-19 at 11 09 01](https://user-images.githubusercontent.com/5557838/90615887-fcfac800-e20c-11ea-9762-da1ec3d2315b.png)

I tested the latest version and it can run and interact normally. You can copy the page into your project for testing.
My dependency package
```
"dependencies": {
     "react": "16.13.1",
     "react-native": "0.63.2",
     "react-native-drag-sort": "^2.3.4"
   },
```
You can copy the code at the address below, and it works normally.
https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/AutomaticSlidingThreePage.js

**Comment by Bavithra** [comment]
the error goes away is I add null check like below,
`this.scrollRef && this.scrollRef.scrollTo({x: 0, y: height, animated})`
in AutoDragSortableView.js line number 574

**Comment by Bavithra** [comment]
> Hello, can I ask some questions?
> premise:
> There will be no problems with my test, and it can run on the latest version of RN.
> problem:
> 
> 1. Was your error triggered before the click triggered the drag, or was it triggered after the click?
> 2. You can print whether this.scrollRef property is empty in the componentDidMount function.
> 3. I want to confirm whether the ref is invalid due to the version, or scrollTo is removed.

the problem arises when I run tests but doesn't happen while doing drag or during rendering. I am using this with hooks

**Comment by mochixuan** [comment]
> the error goes away is I add null check like below,
> `this.scrollRef && this.scrollRef.scrollTo({x: 0, y: height, animated})`
> in AutoDragSortableView.js line number 574

Can you tell me your phone model? If there is a problem, I will fix it tomorrow

**Comment by Bavithra** [comment]
> > the error goes away is I add null check like below,
> > `this.scrollRef && this.scrollRef.scrollTo({x: 0, y: height, animated})`
> > in AutoDragSortableView.js line number 574
> 
> Can you tell me your phone model? If there is a problem, I will fix it tomorrow

I tested with iPhone 8 and iPhone 11

**Comment by mochixuan** [comment]
this.scrollRef is important and must be executed. I will fix it tomorrow

**Comment by mochixuan** [comment]
Are you using the project created by expo-cli or create-react-native-app. I tested the latest version RN@0.63.2. On Android and iOS (8 and 11) they are normal for my demo. I will test the expo-cli project next.

**Comment by apgsn** [comment]
@mochixuan personally I'm using create-react-native-app. The issue appears on both iOS (emulator) and Android (physical device), it probably has to do with the unmount phase, if that makes sense.

**Comment by mochixuan** [comment]
> @mochixuan personally I'm using create-react-native-app. The issue appears on both iOS (emulator) and Android (physical device), it probably has to do with the unmount phase, if that makes sense.

Can you give me a Demo. I tested the latest version. No problem in different systems. I don't know if it is a problem with my example.

**Comment by apgsn** [comment]
I'll get back to you as soon as I have some time to spin up a demo illustrating the problem.

**Comment by mochixuan** [comment]
Fix the "_this.scrollRef" problem of RN@0.63.2.

**Comment by apgsn** [comment]
Still not fixed for me, sorry pal :/

Here's an example.
![scrollTo recording (2)](https://user-images.githubusercontent.com/5557838/90775197-db770a80-e2f8-11ea-93f4-5413eaff073a.gif)

Please note:
- The bug is quite erratic, in the sense that sometimes it doesn't show up. I believe it pops out when the scroll hasn't stopped yet, but even then I cannot replicate it consistently;
- While some images in the example are the same, the actual items are different (that is, each image has a different `uuid` key, which I map in the `keyExtractor`);
- The navbar component is from Native Base, the routing from React Navigation v5.

Still no code, I know, sorry about that. I'll work on this later on and I'll let you know whether I can find a solution.

**Comment by mochixuan** [comment]
> Still not fixed for me, sorry pal :/
> 
> Here's an example.
> ![scrollTo recording (2)](https://user-images.githubusercontent.com/5557838/90775197-db770a80-e2f8-11ea-93f4-5413eaff073a.gif)
> 
> Please note:
> 
> * The bug is quite erratic, in the sense that sometimes it doesn't show up. I believe it pops out when the scroll hasn't stopped yet, but even then I cannot replicate it consistently;
> * While some images in the example are the same, the actual items are different (that is, each image has a different `uuid` key, which I map in the `keyExtractor`);
> * The navbar component is from Native Base, the routing from React Navigation v5.
> 
> Still no code, I know, sorry about that. I'll work on this later on and I'll let you know whether I can find a solution.

You can try on line 574 (this.scrollRef && this.scrollRef.scrollTo({x: 0, y: height, animated})) to see if you can completely fix this problem. If possible, I will temporarily use this method to fix the latest version of the problem

**Comment by apgsn** [comment]
@mochixuan the null check suggested by @Bavithra indeed fixes the problem.

**Comment by Maverick5000** [comment]
Updating to 2.3.4 fixed for me
