### ISSUE TITLE
不是提bug，是一个需求。希望能提供个思路

### ISSUE THREAD

**Issue by CodeRabbitYu** [mochixuan/react-native-drag-sort#80]
要做一个类似淘宝合成猫的效果。  两个卡片合成一张。 我看了库里面都是移动。贴合的时候也没办法覆盖。
希望能给个思路。

**Comment by mochixuan** [comment]
能给个gif参考一下，没太明白你的想法

**Comment by CodeRabbitYu** [comment]
类似淘宝 合成猫的 玩法， 两张卡片，贴在一起就变成了一张卡
![合成](https://user-images.githubusercontent.com/10183022/91005923-ade8d480-e60a-11ea-83cb-54032b3abd75.png)
![合成-按下](https://user-images.githubusercontent.com/10183022/91005926-b04b2e80-e60a-11ea-9110-1ccffde0db7b.png)

**Comment by CodeRabbitYu** [comment]
请问有思路吗？  我在onDragEnd做删除操作，发现会在莫名其妙的地方报错

**Comment by mochixuan** [comment]
首先：非常今天下午太忙了现在才回。
其次：对于onDragEnd问题
1，在onDragEnd做删除可以等100ms等动画结束。
2，在删除时，先对数据进行浅拷贝{...this.state.data}，这样删除一个数据比较好。
最后：
我理解你的需求是：当拖动一个向另一个方向移动的时候，加上1，2，3，4.把上移到2上面。2不能动。触发合成1，23，空，4.
如果需求没有理解错的话，你可能得改下我的代码如果你不需要实现拖到地步需要触发自动滑动的话可以使用DragSortableView改，这个相对稳定和简洁。
如果需求没有理解错误的话，其实你这个可以不需要使用我这个插件。当拖动3时，4是否要向3靠拢如果不需要的话。可以如下。
使用绝对布局对每一个进行定位。当手指按下摸个进行滑动，改变他的left和top,当放手时判断left和top在那个位置。例如3拖动到了2上面(遮盖一半就算合并)。触发合并。之后对新数据进行重新的技术left和top。这样实现会很简单。不知道我的需求理解是否有问题。希望对你有帮助。

**Comment by CodeRabbitYu** [comment]
谢谢回答，我昨天把DragSortableView中动画移动的方法关闭了，还把onDragEnd返回值一道了最后，基本实现了想要的效果。

**Comment by mochixuan** [comment]
也行，如果我理解需求没错，按我思路写，可能更简单。但实现了就好
