### ISSUE TITLE
Pressed state for grid items

### ISSUE THREAD

**Issue by casos92** [mochixuan/react-native-drag-sort#81]
Have you considered adding a pressed state for the grid items before the reorder flow is entered? It would be nice to give the user feedback that their touch is being handled before entering the reorder flow. A simple scale like this would work:

https://media.geeksforgeeks.org/wp-content/uploads/20200107123635/ezgif-6-84a39e005902.gif

**Comment by mochixuan** [comment]
Do you mean adding touch feedback? Or add a shadow effect?

**Comment by casos92** [comment]
Yes touch feedback where the grid item scales down
