### ISSUE TITLE
Dyamic childeren height

### ISSUE THREAD

**Issue by sanjayradadiya** [mochixuan/react-native-drag-sort#82]
Hi,

My list contains the different height of list item so how we can use the dynamic size of children?

**Comment by casos92** [comment]
also looking for a solution to this

**Comment by mochixuan** [comment]
This has not been implemented for the time being, due to different scenarios, and design issues

**Comment by lyseiha** [comment]
so meaning Children can not change height?

**Comment by mochixuan** [comment]
Can't be changed temporarily

**Comment by Philliprince** [comment]
Really hope this can support dynamic height one day.
These marvelous work meet all my expectations except for the fixed width & height.

感觉可以先enable长度的不固定，因为像SortAndFixedPage这种，话题都是两个字的局限性较大，还是希望能够有一个支持。
加油！

**Comment by Svarto** [comment]
Same here, hope it gets support in the future!

**Comment by mochixuan** [comment]
Adaptive size has been developed and drag can be triggered anywhere
