### ISSUE TITLE
Long delay after onDragEnd

### ISSUE THREAD

**Issue by leelandclay** [mochixuan/react-native-drag-sort#84]
I implemented the DragSortableView and everything works, however there's a 7 second delay after the drag ends before anything works again. I added some logging to various points and discovered the onDragEnd method takes about 120 ms to complete. However, it then re-renders 6 times with about 1.2 seconds between each render. The component will not allow any other action until after the 6 renders are complete.

Here's the code for the DragSortableView that I'm using:
```
<DragSortableView
  dataSource={
    subscriptionContext && subscriptionContext.transactionReceipt
      ? this.state.pictures.sort((a, b) => (a.order > b.order ? 1 : -1))
      : this.state.pictures.sort((a, b) => (a.order > b.order ? 1 : -1)).slice(0, 4)
  }
  parentWidth={parentWidth}
  childrenWidth={childrenWidth}
  childrenHeight={childrenHeight}
  marginChildrenTop={marginChildrenTop}
  marginChildrenBottom={marginChildrenBottom}
  marginChildrenLeft={marginChildrenLeft}
  marginChildrenRight={marginChildrenRight}
  isDragFreely={true}
  onDragging={this.onDragging}
  onDragStart={this.handleDragStart}
  onDragEnd={this.onDragEnd}
  onDataChange={this.handleDataChange}
  onClickItem={this.handleClickItem}
  keyExtractor={(item, index) => item.id}
  renderItem={this.renderItem}
/>
```
I'm using version 2.3.7.

**Comment by mochixuan** [comment]
Have not encountered this situation, you can check dataSource, keyExtractor to see if there is a problem with the setting
