### ISSUE TITLE
Add support for ListEmptyComponent in AutoDragSortableView

### ISSUE THREAD

**Issue by jeemin1234** [mochixuan/react-native-drag-sort#85]
Can the prop `ListEmptyComponent` be added to `AutoDragSortableView`?

I'd like to render a specific full screen with error message and icons when there are no contents available to show.  `FlatList` has a prop called `ListEmptyComponent` that allows this and I was wondering if support for this prop (`ListEmptyComponent`) could be added to `AutoDragSortableView` to allow for such behavior.

**Comment by mochixuan** [comment]
This property can be implemented in other ways. For example, items.length !== 0? AutoDragSortableView: ListEmptyComponent, does not need to be implemented in AutoDragSortableView

**Comment by wuxiangqi** [comment]
Can I use AutoDragSortableView twice in one interface?Such as adjusting the ingredients and steps of the recipe? AutoDragSortableView has its own scrolling function. If the ScrollView is wrapped externally, it will cause conflicts. Is there a solution?

**Comment by mochixuan** [comment]
1. You can use two at the same time, but you must deal with the sliding problem yourself.
2. Two AutoDragSortableViews cannot be used on the same screen, and there will be problems with the sliding function.
3. You can use DragSortableView to handle the sliding by yourself. You can refer to https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/CommonSortPage.js
