### ISSUE TITLE
Could MaxScale go below 1?

### ISSUE THREAD

**Issue by seanchristopherjordan** [mochixuan/react-native-drag-sort#86]
Hi there -- when setting MaxScale to, say, 0.80, I get an error -- "InputRange must be monotonically non-decreasing." 

This suggests that tiles when longpressed and then dragged can only stay the same size, or grow. Meantime I've seen some drag 'n' drop UIs that are visually more understandable when the selected tile actually *shrinks* -- you see empty space around the selected item, and it de-clutters the interface quite nicely. 

Anyway, just throwing that out there -- have you considered adding support for that value being below 1.00?

Cheers! Great tool btw.

**Comment by mochixuan** [comment]
Thanks, it can be supported, I will add it as soon as I have time, at the latest on the weekend

**Comment by seanchristopherjordan** [comment]
Hey, that's great news! Thanks so much, will be good to try this out.

**Comment by mochixuan** [comment]
It has been fixed in v2.3.8

**Comment by seanchristopherjordan** [comment]
Thanks so much! Not so much a fix but a feature request. Really appreciate it
