### ISSUE TITLE
Animation is inverted on the horizontal axis on forced RTL apps.

### ISSUE THREAD

**Issue by MahmoudThePeltist** [mochixuan/react-native-drag-sort#88]
**Versions:**
```
"react-native": "0.63.2"
"react-native-drag-sort": "^2.3.8"
```

**Description:**
My app is forced RTL using react-native's `I18nManager.forceRTL(true);` predictably when I press and hold the image starts hovering, but while it moves correctly vertically, it's inverted when we're moving horizontally, so basically if I move left the image goes right, and if I move right, the image moves left.

**Comment by mochixuan** [comment]
In this case, you may need to modify the code, make some modifications according to your needs

**Comment by MahmoudThePeltist** [comment]
Alright, I managed to find a fix for this by using the `transform: [{rotateY: '180deg'}]` style to mirror the container holding the images, the using it again on the images themselves so they don't look flipped. but this feels really hacky to be honest, is there a better way to do it?

**Comment by MahmoudThePeltist** [comment]
> In this case, you may need to modify the code, make some modifications according to your needs

Ah, you mean to modify the component itself, alright I'll see what I can do.
