### ISSUE TITLE
AutoDragSortableView items get jerky sometimes when dragged

### ISSUE THREAD

**Issue by aarondail** [mochixuan/react-native-drag-sort#89]
First of all thanks for the great library.

One issue we have hit is that AutoDragSortableView allows items to be dragged beyond the top and bottom bounds of the view, and (especially on Android) the items get pretty jerky in this case when dragging.

Here is a video of it happening in the Example app:
[jerky.mp4.zip](https://github.com/mochixuan/react-native-drag-sort/files/5460286/jerky.mp4.zip)

A great fix for this would just be to prevent the items from being dragged above the top or below the bottom the list.  I am happy to take a look at providing a fix if you can give me some pointers on what to look for.

I will add that the AutoDragSortableView in _our app_ *sometimes* actually does not allow items to be dragged above or below the list... so its a little inconsistent.  But that could just be something about to our app.  The Example app provided with this library never blocked dragging an item above or below the list when I tested it (for AutoDragSortableView).

**Comment by mochixuan** [comment]
You can use DragSortableView

**Comment by aarondail** [comment]
@mochixuan Hmm well we sorta need the "Auto" scroll bit (since we have a long list)?

**Comment by mochixuan** [comment]
Because the scrollview of Android takes more than 16ms to slide once, on some phones with lower performance, it will cause some freezes. You can use DragSortableView or need to re-implement the animation of the selected item when sliding. Can use absolute
