### ISSUE TITLE
Scroll the view when drag item to the top or bottom of screen

### ISSUE THREAD

**Issue by robynluo** [mochixuan/react-native-drag-sort#9]
How can auto-scroll down or up ScrollView when dragging the item to the bottom or top of the screen?

**Comment by mochixuan** [comment]
> How can auto-scroll down or up ScrollView when dragging the item to the bottom or top of the screen?

This feature has no time to implement, you can refer to react-native-sortable-listview

**Comment by Gaganrana92** [comment]
Remove/ comment this condition from the startAutoScroll() method of the AnySizeDragSortableView.js file.

// Anti-shake 1.x1
if (!this.curScrollData.hasScroll) {
return;
}
