### ISSUE TITLE
Support for horizontal ScrollView

### ISSUE THREAD

**Issue by sevicbb** [mochixuan/react-native-drag-sort#91]
@mochixuan - Great library!

Is there a plan for introducing horizontal property for ScrollView? 

My suggestion is to pass `horizontal` and `showsHorizontalScrollIndicator` from `DragSortableView/AutoDragSortableView` to wrapped ScrollView. 

Also, is there any chance to handle automatic scrolling to left or right, when this is introduced?

**Comment by seanchristopherjordan** [comment]
@sevicbb @mochixuan  -- I second that emotion! Would be tremendously useful.

**Comment by mochixuan** [comment]
Due to busy work recently, the horizontal sliding function may take some time

**Comment by babyrusa** [comment]
Hello, is there any update for horizontal scrollview? Thank you very much

**Comment by mochixuan** [comment]
> Hello, is there any update for horizontal scrollview? Thank you very much

sorry, did not update

**Comment by abdulbasitawan** [comment]
Hello, is there any update for horizontal scrollview? Thank you very much

**Comment by mochixuan** [comment]
> Hello, is there any update for horizontal scrollview? Thank you very much

Sorry, not yet
