### ISSUE TITLE
Adding a drag handle

### ISSUE THREAD

**Issue by MarioUnlam** [mochixuan/react-native-drag-sort#93]
Hi. I need to make a list draggable, but only when the user taps an icon which is present on every item. When holding tap on that icon, there item should become draggable without delay, and tapping anywhere else on the item should not start the dragging. Is there a way to accomplish this? none of the examples show something like that, and it's very common to have dragging handles in vertical lists of items.

**Comment by mochixuan** [comment]
I'm very sorry. Due to the busy work and late reply, you can try to set delaylongpress to 0. You can modify the code this.isMovePanResponder=true Just fine

**Comment by hanwenbo** [comment]
@MarioUnlam  use TouchableOpacity  ,wrap it, no need drag s View
