### ISSUE TITLE
null is not an object (evaluating 'n.touchCurItem.ref')

### ISSUE THREAD

**Issue by wutiange** [mochixuan/react-native-drag-sort#94]
rn: 0.61.5
react: 16.9.0
react-native-drag-sort: 2.1.1

我想是因为动画还没结束就触发进而导致的问题
I think it's the problem caused by the trigger before the animation is over

**Comment by mochixuan** [comment]
升级下到最新的版本就好了

**Comment by wutiange** [comment]
好，谢谢
