### ISSUE TITLE
OneRowsPage 这个模式下，怎么实现左右滑动

### ISSUE THREAD

**Issue by explorefit** [mochixuan/react-native-drag-sort#95]
请问 OneRowsPage 在这个模式下，排序可以正常使用，但是怎么实现左右滑动，类似删除那种

**Comment by mochixuan** [comment]
你好，这个功能是没有的暂时。你可能需要单独去修改源码，或者换个框架。

**Comment by explorefit** [comment]
谢谢你的回复，我会找找其他的方案，你写的这个库真的蛮有用的，希望以后可以加上这个功能，再次非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mochixuan/react-native-drag-sort"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月18日(星期三) 晚上6:31
收件人:&nbsp;"mochixuan/react-native-drag-sort"<react-native-drag-sort@noreply.github.com&gt;;
抄送:&nbsp;"红豆咖啡"<1538718676@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mochixuan/react-native-drag-sort] OneRowsPage 这个模式下，怎么实现左右滑动 (#95)





 
你好，这个功能是没有的暂时。你可能需要单独去修改源码，或者换个框架。
