### ISSUE TITLE
array 2 dimension with fixed title

### ISSUE THREAD

**Issue by hak11** [mochixuan/react-native-drag-sort#96]
i have data like this

```
	const initialData = {
		day1: [
			{
				content_type: 'module',
				title: 'sylabus title 1 content 1',
				summary: 'sylabus summary 1 content 1',
				detail: 'sylabus detail 1 content 1',
			},
			{
				content_type: 'module',
				title: 'sylabus ttile 1 content 2',
				summary: 'sylabus summary 1 content 2',
				detail: 'sylabus detail 1 content 2',
			},
		],
		day2: [
			{
				content_type: 'test',
				title: 'sylabus title 2 content 1',
				detail: 'sylabus detail 2 content 1',
				summary: 'sylabus summary 2 content 1',
			},
		],
	}

```
is it posible to make like this (fixed title)

![Screenshot from 2020-11-20 11-01-57](https://user-images.githubusercontent.com/14852163/99756496-e02da380-2b1f-11eb-823e-e75843b19047.png)

**Comment by mochixuan** [comment]
I don’t quite understand what you want to fix, can you circle it

**Comment by hak11** [comment]
sorry I mean static title

how to create static title with AutoDragSortableView  

![Screenshot from 2020-11-20 11-01-57](https://user-images.githubusercontent.com/14852163/99784591-9f00b800-2b4e-11eb-9fb8-a6ec9ab7c25c.png)

**Comment by mochixuan** [comment]
You can refer to it https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/SortAndFixedPage.js

**Comment by hak11** [comment]
thank you @mochixuan
